{
 "title": "02. Rufgruppen (PostgreSQL)",
 "description": "Ring group dashboard analytics",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "ring_group",
    "label": "Ring group",
    "query": "WITH rg AS (\n  SELECT\n    rg.destination_dn_number AS dn_number,\n    COALESCE(rg.destination_dn_name, 'Unknown') AS name,\n    ROW_NUMBER() OVER (PARTITION BY rg.destination_dn_number ORDER BY rg.cdr_started_at DESC) AS row_num\n  FROM public.cdroutput AS rg\n  WHERE rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n  AND rg.destination_dn_number IS NOT NULL\n  AND rg.cdr_started_at >= NOW() - INTERVAL '365 days' -- Changed CURRENT_TIMESTAMP to NOW() and INTERVAL syntax\n)\nSELECT\n  rg.dn_number || ' ' || rg.name AS __text,\n  rg.dn_number AS __value\nFROM rg\nWHERE rg.row_num = 1\nORDER BY __value;"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ${ring_group:text}" } },
  {
   "title": "Eingegangene Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der eingegangenen Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  COUNT(DISTINCT rg.cdr_id) AS total_calls\nFROM public.cdroutput AS rg\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  COUNT(DISTINCT\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n      THEN rg.cdr_id\n    END\n  ) AS answered_calls\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  COUNT(DISTINCT\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n      THEN rg.cdr_id\n    END\n  ) * 100.0 /\n  NULLIF(COUNT(DISTINCT rg.cdr_id), 0)\n  AS percent_answered\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  COALESCE(COUNT(DISTINCT rg.cdr_id), 0) -\n  COALESCE(COUNT(DISTINCT\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n      THEN rg.cdr_id\n    END\n  ), 0)\n  AS unanswered_calls\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  SUM(\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n      THEN EXTRACT(EPOCH FROM (continued_in_cdr.cdr_ended_at - continued_in_cdr.cdr_answered_at))\n    END\n  ) AS total_talking_time\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  AVG(\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n      THEN EXTRACT(EPOCH FROM (continued_in_cdr.cdr_ended_at - continued_in_cdr.cdr_answered_at))\n    END\n  ) AS total_talking_time\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  AVG(\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN EXTRACT(EPOCH FROM (continued_in_cdr.cdr_ended_at - rg.cdr_started_at))\n      ELSE EXTRACT(EPOCH FROM (rg.cdr_ended_at - rg.cdr_started_at))\n    END\n  ) AS duration\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Längste Anrufdauer",
   "type": "stat",
   "description": "Dauer des längsten Anrufs im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  MAX(\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN EXTRACT(EPOCH FROM (continued_in_cdr.cdr_ended_at - rg.cdr_started_at))\n      ELSE EXTRACT(EPOCH FROM (rg.cdr_ended_at - rg.cdr_started_at))\n    END\n  ) AS duration\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "% Verpasste Anrufe",
   "type": "gauge",
   "description": "Prozentualer Anteil nicht angenommener Anrufe",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  COUNT(DISTINCT\n    CASE\n      WHEN NOT (rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension')\n      THEN rg.cdr_id\n    END\n  ) * 100.0 /\n  NULLIF(COUNT(DISTINCT rg.cdr_id), 0)\n  AS missed_call_rate\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Ø Klingelzeit",
   "type": "stat",
   "description": "Durchschnittliche Wartezeit bis zur Annahme",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  AVG(EXTRACT(EPOCH FROM (rg.cdr_ended_at - rg.cdr_started_at))) AS duration\nFROM public.cdroutput AS rg\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Anrufergebnis",
   "type": "piechart",
   "description": "Verteilung der Anrufergebnisse (angenommen, verpasst, etc.)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN COALESCE(continued_in_cdr.termination_reason, 'other')\n      ELSE COALESCE('not_answered__' || rg.termination_reason, 'other')\n    END\n    AS call_outcome,\n    COUNT(*) AS call_count\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY call_outcome\nORDER BY call_count DESC\n;"
    }
   ]
  },
  {
   "title": "Eingegangene / Angenommene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Zeitlicher Vergleich von eingegangenen und angenommenen Anrufen",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n    DATE_TRUNC('hour', rg.cdr_started_at) AS \"time\",\n    COUNT(DISTINCT rg.cdr_id) AS total_calls,\n    COUNT(DISTINCT\n    CASE\n        WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN rg.cdr_id\n    END\n    ) AS answered_calls\nFROM public.cdroutput AS rg\nLEFT JOIN public.cdroutput AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY 1\nORDER BY 1\n;"
    }
   ]
  },
  {
   "title": "Rufgruppen-Statistik",
   "type": "table",
   "description": "Ring group call statistics",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "-- Ring group info with last name\nWITH rg_info AS (\n  SELECT\n    rg.destination_dn_number AS dn_number,\n    CASE WHEN '${ring_group:value}' = 'All' THEN 'All ring groups' ELSE COALESCE(rg.destination_dn_name, 'Unknown') END AS name\n  FROM public.cdroutput AS rg\n  WHERE rg.cdr_started_at = ( -- Changed this line\n    SELECT\n      MAX(sub_rg.cdr_started_at) -- Changed this to MAX(cdr_started_at)\n    FROM public.cdroutput AS sub_rg\n    WHERE $__timeFilter(sub_rg.cdr_started_at)\n      AND ('${ring_group:value}' = 'All' OR sub_rg.destination_dn_number = '${ring_group:value}')\n      AND sub_rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n  )\n),\n-- Ring group totals\nrg_totals AS (\n  SELECT\n    0 AS row_order_no,\n    MAX(rg.destination_dn_number) AS rg_dn,\n    MAX(rg_info.name) AS rg_name,\n    COUNT(DISTINCT rg.cdr_id) AS rg_received_count,\n    COUNT(DISTINCT\n      CASE\n        WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN rg.cdr_id\n      END\n    ) AS rg_answered_count\n  FROM public.cdroutput AS rg\n  INNER JOIN rg_info ON TRUE \n  LEFT JOIN public.cdroutput AS continued_in_cdr ON\n    continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n    AND continued_in_cdr.creation_forward_reason = 'polling'\n  WHERE $__timeFilter(rg.cdr_started_at)\n    AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n    AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n  GROUP BY rg.destination_dn_number -- Added GROUP BY for rg_totals\n),\n-- Ring group users statistics\nrg_users_stat AS (\n  SELECT\n    1 AS row_order_no,\n    MAX(rg.destination_dn_number) AS rg_dn,\n    MAX(rg_info.name) AS rg_name,\n    agent_polls.destination_dn_number AS agent_dn,\n    COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent_name,\n    COUNT(DISTINCT CASE WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN rg.cdr_id END) AS agent_answered_polls_count,\n    COUNT(agent_polls.cdr_id) AS agent_received_polls_count\n  FROM public.cdroutput AS rg\n  INNER JOIN rg_info ON TRUE -- This will cause issues if rg_info returns multiple rows. See note below.\n  INNER JOIN public.cdroutput AS agent_polls ON\n    agent_polls.call_history_id = rg.call_history_id\n    AND agent_polls.originating_cdr_id = rg.cdr_id\n    AND agent_polls.destination_dn_type = 'extension'\n    AND agent_polls.creation_method = 'route_to'\n    AND agent_polls.creation_forward_reason = 'polling'\n  WHERE $__timeFilter(rg.cdr_started_at)\n    AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n    AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n  GROUP BY agent_polls.destination_dn_number, agent_polls.destination_dn_name, rg.destination_dn_number -- Added rg.destination_dn_number to GROUP BY\n)\nSELECT\n  rg.row_order_no,\n  CASE WHEN '${ring_group:value}' != 'All' THEN rg.rg_dn || ' ' ELSE '' END || rg.rg_name || ' [totals]' AS extension,\n  COALESCE(rg.rg_received_count, 0) AS calls_received,\n  COALESCE(rg.rg_received_count, 0) - COALESCE(rg.rg_answered_count, 0) AS calls_unanswered,\n  COALESCE(rg.rg_answered_count, 0) AS calls_answered,\n  CAST(NULL AS bigint) AS polls_received,\n  CAST(NULL AS bigint) AS polls_missed\nFROM rg_totals AS rg\nUNION ALL\nSELECT\n  u.row_order_no,\n  u.agent_dn || ' ' || u.agent_name AS extension,\n  CAST(NULL AS bigint) AS calls_received,\n  CAST(NULL AS bigint) AS calls_unanswered,\n  COALESCE(u.agent_answered_polls_count, 0) AS calls_answered,\n  COALESCE(u.agent_received_polls_count, 0) AS polls_received,\n  COALESCE(u.agent_received_polls_count, 0) - COALESCE(u.agent_answered_polls_count, 0) AS polls_missed\nFROM rg_users_stat AS u\nORDER BY row_order_no, extension;"
    }
   ]
  },
  {
   "title": "Eingegangene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Time series Graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n    DATE_TRUNC('hour', rg.cdr_started_at) AS \"time\",\n    COUNT(DISTINCT rg.cdr_id) AS num_calls\nFROM public.cdroutput AS rg\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY 1\nORDER BY 1\n;"
    }
   ]
  },
  {
   "title": "Anrufstatistik nach Rufgruppenmitgliedern",
   "type": "barchart",
   "description": "This shows the number of answered calls per extension in the ring group.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "SELECT\n  agent_polls.destination_dn_number || ' ' || COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent,\n  COUNT(DISTINCT agent_polls.main_call_history_id) AS agent_received_calls_count,\n  COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\n  COUNT(DISTINCT CASE WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN rg.cdr_id END) AS agent_answered_polls_count\nFROM public.cdroutput AS rg\nINNER JOIN public.cdroutput AS agent_polls ON\n  agent_polls.call_history_id = rg.call_history_id\n  AND agent_polls.originating_cdr_id = rg.cdr_id\n  AND agent_polls.destination_dn_type = 'extension'\n  AND agent_polls.creation_method = 'route_to'\n  AND agent_polls.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\n  AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n  AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY agent\nORDER BY agent\n;"
    }
   ]
  }
 ]
}