{
 "title": "14. Häufige eingehende Anrufer (PostgreSQL)",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "inbound_caller",
    "label": "Inbound Caller",
    "query": "----------------------\n-- Inbound connections\n----------------------\nWITH inbound_connections AS (\n\t---------\n\t-- Source\n\t---------\n\tSELECT\n\t\tc.source_participant_id AS participant_id,\n\t\tc.source_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS participant\n\tFROM public.cdroutput AS c\n\tLEFT JOIN public.cdroutput AS c_orig ON\n\t\tc_orig.cdr_id = c.originating_cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND\n\t(\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type = 'inbound_routing'\n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t\tAND c.termination_reason != 'continued_in'\n\t\t\tAND c.continued_in_cdr_id IS NULL\n\t\t)\n\t\tOR\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t)\n\t)\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\n\t--AND c.cdr_answered_at IS NOT NULL\n\tUNION ALL\n\t--------------\n\t-- Destination\n\t--------------\n\tSELECT\n\t\tc.destination_participant_id AS participant_id,\n\t\tc.destination_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS participant\n\tFROM public.cdroutput AS c\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND c.destination_entity_type = 'external_line'\n\tAND c.destination_participant_is_incoming\n\t--AND c.cdr_answered_at IS NOT NULL\n)\nSELECT\n\tc.participant AS __text,\n\tMIN(c.participant_phone_number) AS __value\n\t--,COUNT(DISTINCT c.participant_id)\nFROM inbound_connections AS c\nGROUP BY c.participant\nORDER BY COUNT(DISTINCT c.participant_id) DESC\nLIMIT 100\n;"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Häufige eingehende Anrufer" } },
  {
   "title": "Top 100 häufigste Anrufer (nach Anzahl)",
   "type": "barchart",
   "description": "Die 100 Rufnummern mit den meisten eingehenden Anrufen",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "----------------------\n-- Inbound connections\n----------------------\nWITH inbound_connections AS (\n\t---------\n\t-- Source\n\t---------\n\tSELECT\n\t\tc.source_participant_id AS participant_id,\n\t\tc.source_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS participant\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tLEFT JOIN public.cdroutput AS c_orig ON\n\t\tc_orig.cdr_id = c.originating_cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\n\tAND\n\t(\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type = 'inbound_routing'\n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t\tAND c.termination_reason != 'continued_in'\n\t\t\tAND c.continued_in_cdr_id IS NULL\n\t\t)\n\t\tOR\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t)\n\t)\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\n\t--AND c.cdr_answered_at IS NOT NULL\n\tUNION ALL\n\t--------------\n\t-- Destination\n\t--------------\n\tSELECT\n\t\tc.destination_participant_id AS participant_id,\n\t\tc.destination_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS participant\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\n\tAND c.destination_entity_type = 'external_line'\n\tAND c.destination_participant_is_incoming\n\t--AND c.cdr_answered_at IS NOT NULL\n)\nSELECT\n\tc.participant AS participant,\n\tCOUNT(DISTINCT c.participant_id) AS participant_count\nFROM inbound_connections AS c\nGROUP BY c.participant\nORDER BY COUNT(DISTINCT c.participant_id) DESC\nLIMIT 100\n;"
    }
   ]
  },
  {
   "title": "Top 100 häufigste Anrufer (nach Gesprächsdauer)",
   "type": "barchart",
   "description": "Die 100 Rufnummern mit der längsten Gesamtgesprächsdauer",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "----------------------\n-- Inbound connections\n----------------------\nWITH inbound_connections AS (\n\t---------\n\t-- Source\n\t---------\n\tSELECT\n\t\tc.source_participant_id AS participant_id,\n\t\tc.source_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS participant,\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') AND c.cdr_answered_at IS NOT NULL THEN EXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_answered_at)) ELSE 0 END AS talking_duration\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tLEFT JOIN public.cdroutput AS c_orig ON\n\t\tc_orig.cdr_id = c.originating_cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\n\tAND\n\t(\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type = 'inbound_routing'\n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t\tAND c.termination_reason != 'continued_in'\n\t\t\tAND c.continued_in_cdr_id IS NULL\n\t\t)\n\t\tOR\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t)\n\t)\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\n\t--AND c.cdr_answered_at IS NOT NULL\n\tUNION ALL\n\t--------------\n\t-- Destination\n\t--------------\n\tSELECT\n\t\tc.destination_participant_id AS participant_id,\n\t\tc.destination_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS participant,\n\t\tCASE WHEN c.cdr_answered_at IS NOT NULL THEN coalesce(EXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_answered_at)), 0) ELSE 0 END AS talking_duration\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\n\tAND c.destination_entity_type = 'external_line'\n\tAND c.destination_participant_is_incoming\n\t--AND c.cdr_answered_at IS NOT NULL\n)\nSELECT\n\tc.participant AS participant,\n\tSUM(c.talking_duration) AS talking_duration\nFROM inbound_connections AS c\nGROUP BY c.participant\nORDER BY SUM(c.talking_duration) DESC\nLIMIT 100\n;"
    }
   ]
  },
  {
   "title": "Anrufverlauf",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf der Anrufanzahl im gewählten Zeitraum",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "----------------------\n-- Inbound connections\n----------------------\nWITH inbound_connections AS (\n\t---------\n\t-- Source\n\t---------\n\tSELECT\n\t\tc.cdr_started_at AS started_at,\n\t\tc.source_participant_id AS participant_id,\n\t\tc.source_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS participant\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tLEFT JOIN public.cdroutput AS c_orig ON\n\t\tc_orig.cdr_id = c.originating_cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\n\tAND\n\t(\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type = 'inbound_routing'\n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t\tAND c.termination_reason != 'continued_in'\n\t\t\tAND c.continued_in_cdr_id IS NULL\n\t\t)\n\t\tOR\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t)\n\t)\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\n\t--AND c.cdr_answered_at IS NOT NULL\n\tUNION ALL\n\t--------------\n\t-- Destination\n\t--------------\n\tSELECT\n\t\tc.cdr_started_at AS started_at,\n\t\tc.destination_participant_id AS participant_id,\n\t\tc.destination_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS participant\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\n\tAND c.destination_entity_type = 'external_line'\n\tAND c.destination_participant_is_incoming\n\t--AND c.cdr_answered_at IS NOT NULL\n)\nSELECT\n\tDATE_TRUNC('hour', c.started_at) AS time,\n\tc.participant AS participant,\n\tCOUNT(DISTINCT c.participant_id) AS \"Calls\"\nFROM inbound_connections AS c\nGROUP BY\n\tDATE_TRUNC('hour', c.started_at),\n\tc.participant\nORDER BY time\n;"
    }
   ]
  },
  {
   "title": "Gesprächsdauer (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf der Gesprächsdauer häufiger Anrufer",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "----------------------\n-- Inbound connections\n----------------------\nWITH inbound_connections AS (\n\t---------\n\t-- Source\n\t---------\n\tSELECT\n\t\tc.cdr_started_at AS started_at,\n\t\tc.source_participant_id AS participant_id,\n\t\tc.source_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS participant,\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') AND c.cdr_answered_at IS NOT NULL THEN EXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_answered_at)) ELSE 0 END AS talking_duration\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tLEFT JOIN public.cdroutput AS c_orig ON\n\t\tc_orig.cdr_id = c.originating_cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\n\tAND\n\t(\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type = 'inbound_routing'\n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t\tAND c.termination_reason != 'continued_in'\n\t\t\tAND c.continued_in_cdr_id IS NULL\n\t\t)\n\t\tOR\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t)\n\t)\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\n\t--AND c.cdr_answered_at IS NOT NULL\n\tUNION ALL\n\t--------------\n\t-- Destination\n\t--------------\n\tSELECT\n\t\tc.cdr_started_at AS started_at,\n\t\tc.destination_participant_id AS participant_id,\n\t\tc.destination_participant_phone_number AS participant_phone_number,\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS participant,\n\t\tCASE WHEN c.cdr_answered_at IS NOT NULL THEN coalesce(EXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_answered_at)), 0) ELSE 0 END AS talking_duration\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\n\tAND c.destination_entity_type = 'external_line'\n\tAND c.destination_participant_is_incoming\n\t--AND c.cdr_answered_at IS NOT NULL\n)\nSELECT\n\tDATE_TRUNC('hour', c.started_at) AS time,\n\tc.participant AS participant,\n\tSUM(c.talking_duration) AS \"Talking duration\"\nFROM inbound_connections AS c\nGROUP BY\n\tDATE_TRUNC('hour', c.started_at),\n\tc.participant\nORDER BY time\n;"
    }
   ]
  },
  {
   "title": "Liste eingehender Anrufe",
   "type": "table",
   "description": "Detaillierte Liste aller eingehenden Anrufe der häufigsten Anrufer",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "cdr",
     "rawSql": "----------------------\n-- Inbound connections\n----------------------\nWITH inbound_connections AS (\n\t---------\n\t-- Source\n\t---------\n\tSELECT\n\t\tc.main_call_history_id,\n\t\t--\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS source_participant,\n\t\t--\n\t\tcoalesce(c.source_participant_trunk_did, 'Unknown') AS did,\n\t\t--\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS destination_participant,\n\t\t--\n    c.cdr_started_at AS started_at,\n\t\tc.cdr_answered_at AS answered_at,\n\t\tc.cdr_ended_at AS ended_at,\n\t\tEXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_started_at)) AS duration,\n\t\tEXTRACT(EPOCH FROM (coalesce(c.cdr_answered_at, c.cdr_ended_at) - c.cdr_started_at)) AS ringing_duration,\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN EXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_answered_at)) ELSE 0 END AS talking_duration,\n\t\t0.00 AS bill_cost\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tLEFT JOIN public.cdroutput AS c_orig ON\n\t\tc_orig.cdr_id = c.originating_cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\n\tAND\n\t(\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type = 'inbound_routing'\n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t\tAND c.termination_reason != 'continued_in'\n\t\t\tAND c.continued_in_cdr_id IS NULL\n\t\t)\n\t\tOR\n\t\t(\t\n\t\t\tc.source_entity_type = 'external_line' \n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \n\t\t\tAND c.source_participant_is_incoming = TRUE\n\t\t)\n\t)\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\n\t--AND c.cdr_answered_at IS NOT NULL\n\tUNION ALL\n\t--------------\n\t-- Destination\n\t--------------\n\tSELECT\n\t\tc.main_call_history_id,\n\t\t--\n\t\tCASE\n\t\t\tWHEN c.destination_entity_type = 'external_line'\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\n\t\tEND AS source_participant,\n\t\t--\n\t\tcoalesce(c.destination_participant_trunk_did, 'Unknown') AS did,\n\t\t--\n\t\tCASE\n\t\t\tWHEN c.source_entity_type = 'external_line'\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\n\t\tEND AS destination_participant,\n\t\t--\n    c.cdr_started_at AS started_at,\n\t\tc.cdr_answered_at AS answered_at,\n\t\tc.cdr_ended_at AS ended_at,\n\t\tEXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_started_at)) AS duration,\n\t\tEXTRACT(EPOCH FROM (coalesce(c.cdr_answered_at, c.cdr_ended_at) - c.cdr_started_at)) AS ringing_duration,\n\t\tcoalesce(EXTRACT(EPOCH FROM (c.cdr_ended_at - c.cdr_answered_at)), 0) AS talking_duration,\n\t\t0.00 AS bill_cost\n\tFROM public.cdroutput AS c\n\t-- LEFT JOIN public.cdrbilling AS b ON\n\t-- \tb.cdr_id = c.cdr_id\n\tWHERE $__timeFilter(c.cdr_started_at)\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\n\tAND c.destination_entity_type = 'external_line'\n\tAND c.destination_participant_is_incoming\n\t--AND c.cdr_answered_at IS NOT NULL\n),\nstat AS (\n\tSELECT\n\t\tROW_NUMBER() OVER(ORDER BY c.started_at DESC) AS id1,\n\t\tCASE WHEN (ROW_NUMBER() OVER(PARTITION BY c.main_call_history_id ORDER BY c.started_at DESC) - 1) > 0 THEN 1 ELSE 0 END AS id2,\n\t\t*\n\tFROM inbound_connections AS c\n)\nSELECT\n\t(c.id1 - SUM(c.id2) OVER(ORDER BY c.started_at DESC)) % 2 AS gen_call_id,\n\tc.main_call_history_id,\n\tc.source_participant,\n\tc.did,\n\tc.destination_participant,\n\tc.started_at,\n\tc.answered_at,\n\tc.ended_at,\n\tc.duration,\n\tc.ringing_duration,\n\tc.talking_duration,\n\tc.bill_cost\nFROM stat AS c\nORDER BY c.started_at DESC\n;"
    }
   ]
  }
 ]
}