{
 "title": "01. Überblick (MySQL)",
 "description": "Landing Dashboard and call overview information",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# 3CX Anrufübersicht" } },
  {
   "title": "Gesamtanzahl Anrufe",
   "type": "stat",
   "description": "Gesamtzahl aller Anrufe im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT t.main_call_history_id) AS total_calls\r\nFROM\r\n  public_cdroutput AS t\r\nWHERE $__timeFilter(t.cdr_started_at)\r\n;"
    }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH cdrs AS (\r\n    SELECT\r\n        c.cdr_answered_at,\r\n        ROW_NUMBER() OVER (PARTITION BY c.main_call_history_id ORDER BY c.cdr_id DESC) AS row_num\r\n    FROM public_cdroutput AS c\r\n    WHERE $__timeFilter(c.cdr_started_at)\r\n)\r\nSELECT COUNT(*) AS answered_calls\r\nFROM cdrs\r\nWHERE row_num = 1\r\nAND cdr_answered_at IS NOT NULL;"
    }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH cdrs AS (\r\n\tSELECT\r\n\t\tc.cdr_answered_at,\r\n\t\tROW_NUMBER() OVER (PARTITION BY c.main_call_history_id ORDER BY c.cdr_id DESC) AS row_num\t\t-- 1 = last cdr\r\n\tFROM public_cdroutput AS c\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n)\r\nSELECT\r\n\t(COUNT(CASE WHEN c.cdr_answered_at IS NOT NULL THEN 1 END) * 100.0) / COUNT(*) AS percent_answered\r\nFROM cdrs AS c\r\nWHERE c.row_num = 1                 -- 1 = last cdr\r\nHAVING COUNT(*) > 0\r\n;"
    }
   ]
  },
  {
   "title": "Nicht angenommen",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH cdrs AS (\r\n\tSELECT\r\n\t\tc.cdr_answered_at,\r\n\t\tROW_NUMBER() OVER (PARTITION BY c.main_call_history_id ORDER BY c.cdr_id DESC) AS row_num\t\t-- 1 = last cdr\r\n\tFROM public_cdroutput AS c\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n)\r\nSELECT count(*) AS unanswered_calls\r\nFROM cdrs AS c\r\nWHERE c.row_num = 1                 -- 1 = last cdr\r\nAND c.cdr_answered_at IS NULL\r\n;"
    }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT \r\n    SUM(TIMESTAMPDIFF(SECOND, t.cdr_answered_at, t.cdr_ended_at)) AS total_talking_duration\r\nFROM public_cdroutput AS t\r\nWHERE $__timeFilter(t.cdr_started_at);"
    }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT \r\n    SUM(TIMESTAMPDIFF(SECOND, t.cdr_answered_at, t.cdr_ended_at)) / NULLIF(COUNT(DISTINCT t.main_call_history_id), 0) AS avg_talking_duration\r\nFROM public_cdroutput AS t\r\nWHERE $__timeFilter(t.cdr_started_at)\r\n;"
    }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH calls AS (\r\n  SELECT\r\n    t.main_call_history_id,\r\n    TIMESTAMPDIFF(SECOND, MIN(t.cdr_started_at), MAX(t.cdr_ended_at)) AS duration\r\n  FROM public_cdroutput AS t\r\n  WHERE $__timeFilter(t.cdr_started_at)\r\n  GROUP BY t.main_call_history_id\r\n)\r\nSELECT\r\n  AVG(c.duration) AS avg_call_duration\r\nFROM calls AS c\r\n;"
    }
   ]
  },
  {
   "title": "Längste Anrufdauer",
   "type": "stat",
   "description": "Dauer des längsten Anrufs im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH calls AS (\r\n  SELECT\r\n    t.main_call_history_id,\r\n    TIMESTAMPDIFF(SECOND, MIN(t.cdr_started_at), MAX(t.cdr_ended_at)) AS duration\r\n  FROM public_cdroutput AS t\r\n  WHERE $__timeFilter(t.cdr_started_at)\r\n  GROUP BY t.main_call_history_id\r\n)\r\nSELECT\r\n  MAX(c.duration) AS longest_call_duration\r\nFROM calls AS c\r\n;"
    }
   ]
  },
  {
   "title": "% Verpasste Anrufe (Durchwahl)",
   "type": "gauge",
   "description": "Prozentualer Anteil der verpassten Anrufe auf Durchwahlen",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH all_calls_count AS (\r\n    SELECT\r\n        COUNT(DISTINCT t.main_call_history_id) AS total_count\r\n    FROM public_cdroutput AS t\r\n    WHERE $__timeFilter(t.cdr_started_at)\r\n    AND t.destination_entity_type = 'extension'\r\n),\r\nmissed_calls_count AS (\r\n    SELECT\r\n        COUNT(DISTINCT t.main_call_history_id) AS missed_count\r\n    FROM public_cdroutput AS t\r\n    WHERE t.cdr_answered_at IS NULL\r\n    AND $__timeFilter(t.cdr_started_at)\r\n    AND t.destination_entity_type = 'extension'\r\n)\r\nSELECT\r\n    missed_calls_count.missed_count * 100.0 / NULLIF(all_calls_count.total_count, 0) AS missed_call_rate\r\nFROM all_calls_count, missed_calls_count\r\n;"
    }
   ]
  },
  {
   "title": "Abschlussgründe",
   "type": "piechart",
   "description": "Übersicht der Gründe, aus denen Anrufe beendet wurden",
   "gridPos": { "h": 9, "w": 6, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "WITH cdrs AS (\r\n\tSELECT\r\n\t\tc.termination_reason,\r\n\t\tROW_NUMBER() OVER (PARTITION BY c.main_call_history_id ORDER BY c.cdr_id DESC) AS row_num\t\t-- 1 = last cdr\r\n\tFROM public_cdroutput AS c\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n)\r\nSELECT\r\n    c.termination_reason,\r\n    count(*) AS count\r\nFROM cdrs AS c\r\nWHERE c.row_num = 1                 -- 1 = last cdr\r\nAND c.termination_reason IS NOT NULL\r\nGROUP BY termination_reason\r\nORDER BY count DESC\r\n;"
    }
   ]
  },
  {
   "title": "Anrufverlauf",
   "type": "barchart",
   "description": "Time series Graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT \r\n    STR_TO_DATE(DATE_FORMAT(t.cdr_started_at, '%Y-%m-%d %H:00:00'), '%Y-%m-%d %H:%i:%s') AS time,\r\n    COUNT(DISTINCT t.main_call_history_id) AS num_calls\r\nFROM public_cdroutput AS t\r\nWHERE $__timeFilter(t.cdr_started_at)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Top 10 meistgewählte Nummern",
   "type": "barchart",
   "description": "Top 10 most dialed numbers",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT \r\n    CASE WHEN c.destination_participant_phone_number IS NULL OR c.destination_participant_phone_number = '' THEN c.destination_dn_number ELSE c.destination_participant_phone_number END AS destination_dn_number, \r\n    COUNT(DISTINCT c.main_call_history_id) AS call_count\r\nFROM public_cdroutput AS c\r\nWHERE $__timeFilter(c.cdr_started_at)\r\nAND c.destination_dn_number NOT IN ('EndCall', 'QCB')\r\nGROUP BY CASE WHEN c.destination_participant_phone_number IS NULL OR c.destination_participant_phone_number = '' THEN c.destination_dn_number ELSE c.destination_participant_phone_number END\r\nORDER BY call_count DESC\r\nLIMIT 10\r\n;"
    }
   ]
  },
  {
   "title": "Top 10 aktive Durchwahlen",
   "type": "barchart",
   "description": "Top 10 answered extensions",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT \r\n    destination_dn_number, \r\n    COUNT(*) AS call_count\r\nFROM public_cdroutput\r\nWHERE $__timeFilter(cdr_started_at)\r\nAND destination_entity_type = 'extension'\r\nAND cdr_answered_at IS NOT NULL\r\nGROUP BY destination_dn_number\r\nORDER BY call_count DESC\r\nLIMIT 10\r\n;"
    }
   ]
  },
  {
   "title": "Top 10 Durchwahlen mit verpassten Anrufen",
   "type": "barchart",
   "description": "Top 10 extensions with missed calls",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT \r\n    destination_dn_number, \r\n    COUNT(*) AS call_count\r\nFROM public_cdroutput\r\nWHERE $__timeFilter(cdr_started_at)\r\nAND destination_entity_type = 'extension'\r\nAND cdr_answered_at IS NULL\r\nGROUP BY destination_dn_number\r\nORDER BY call_count DESC\r\nLIMIT 10\r\n;"
    }
   ]
  }
 ]
}