{
 "title": "02. Rufgruppen (MySQL)",
 "description": "Ring group dashboard analytics",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "ring_group",
    "label": "Ring group",
    "query": "WITH rg AS (\n  SELECT\n    rg.destination_dn_number AS dn_number,\n    COALESCE(rg.destination_dn_name, 'Unknown') AS name,\n    ROW_NUMBER() OVER (PARTITION BY rg.destination_dn_number ORDER BY rg.cdr_started_at DESC) AS row_num\n  FROM public_cdroutput AS rg\n  WHERE rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n    AND rg.destination_dn_number IS NOT NULL\n    AND rg.cdr_started_at >= NOW() - INTERVAL 365 DAY\n)\nSELECT\n  CONCAT(rg.dn_number, ' ', rg.name) AS __text,\n  rg.dn_number AS __value\nFROM rg\nWHERE rg.row_num = 1\nORDER BY __value;"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ${ring_group:text}" } },
  {
   "title": "Eingegangene Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der eingegangenen Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT rg.cdr_id) AS total_calls\r\nFROM public_cdroutput AS rg\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN rg.cdr_id\r\n    END\r\n  ) AS answered_calls\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN rg.cdr_id\r\n    END\r\n  ) * 100.0 /\r\n  NULLIF(COUNT(DISTINCT rg.cdr_id), 0)\r\n  AS percent_answered\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  COALESCE(COUNT(DISTINCT rg.cdr_id), 0) -\r\n  COALESCE(COUNT(DISTINCT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN rg.cdr_id\r\n    END\r\n  ), 0)\r\n  AS unanswered_calls\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  coalesce(SUM(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMPDIFF(SECOND, continued_in_cdr.cdr_answered_at, continued_in_cdr.cdr_ended_at)\r\n      ELSE 0\r\n    END\r\n  ), 0) AS total_talking_time\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr\r\n  ON continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\n  AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\n  AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  coalesce(AVG(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMPDIFF(SECOND, continued_in_cdr.cdr_answered_at, continued_in_cdr.cdr_ended_at)\r\n    END\r\n  ), 0) AS total_talking_time\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  coalesce(AVG(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMPDIFF(SECOND, rg.cdr_started_at, continued_in_cdr.cdr_ended_at)\r\n      ELSE TIMESTAMPDIFF(SECOND, rg.cdr_started_at, rg.cdr_ended_at)\r\n    END\r\n  ), 0) AS duration\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Längste Anrufdauer",
   "type": "stat",
   "description": "Dauer des längsten Anrufs im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  coalesce(MAX(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMPDIFF(SECOND, rg.cdr_started_at, continued_in_cdr.cdr_ended_at)\r\n      ELSE TIMESTAMPDIFF(SECOND, rg.cdr_started_at, rg.cdr_ended_at)\r\n    END\r\n  ), 0) AS duration\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "% Verpasste Anrufe",
   "type": "gauge",
   "description": "Prozentualer Anteil nicht angenommener Anrufe",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT\r\n    CASE\r\n      WHEN NOT (rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension')\r\n      THEN rg.cdr_id\r\n    END\r\n  ) * 100.0 /\r\n  NULLIF(COUNT(DISTINCT rg.cdr_id), 0)\r\n  AS missed_call_rate\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Ø Klingelzeit",
   "type": "stat",
   "description": "Durchschnittliche Wartezeit bis zur Annahme",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  coalesce(AVG(TIMESTAMPDIFF(SECOND, rg.cdr_started_at, rg.cdr_ended_at)), 0) AS duration\r\nFROM public_cdroutput AS rg\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Anrufergebnis",
   "type": "piechart",
   "description": "Verteilung der Anrufergebnisse (angenommen, verpasst, etc.)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN COALESCE(continued_in_cdr.termination_reason, 'other')\r\n      ELSE COALESCE(CONCAT('not_answered__', rg.termination_reason), 'other')\r\n    END\r\n    AS call_outcome,\r\n    COUNT(*) AS call_count\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nGROUP BY call_outcome\r\nORDER BY call_count DESC\r\n;"
    }
   ]
  },
  {
   "title": "Eingegangene / Angenommene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Zeitlicher Vergleich von eingegangenen und angenommenen Anrufen",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n    STR_TO_DATE(DATE_FORMAT(rg.cdr_started_at, '%Y-%m-%d %H:00:00'), '%Y-%m-%d %H:%i:%s') AS time,\r\n    COUNT(DISTINCT rg.cdr_id) AS total_calls,\r\n    COUNT(DISTINCT\r\n    CASE\r\n        WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN rg.cdr_id\r\n    END\r\n    ) AS answered_calls\r\nFROM public_cdroutput AS rg\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nGROUP BY 1\r\nORDER BY 1\r\n;"
    }
   ]
  },
  {
   "title": "Rufgruppen-Statistik",
   "type": "table",
   "description": "Ring group call statistics",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- Ring group info with last name\r\nWITH rg_info AS (\r\n  SELECT\r\n    rg.destination_dn_number AS dn_number,\r\n    CASE WHEN '${ring_group:value}' = 'All' THEN 'All ring groups' ELSE COALESCE(rg.destination_dn_name, 'Unknown') END AS name\r\n  FROM public_cdroutput AS rg\r\n  WHERE rg.cdr_started_at = ( -- Changed this line\r\n    SELECT\r\n      MAX(sub_rg.cdr_started_at) -- Changed this to MAX(cdr_started_at)\r\n    FROM public_cdroutput AS sub_rg\r\n    WHERE $__timeFilter(sub_rg.cdr_started_at)\r\n      AND ('${ring_group:value}' = 'All' OR sub_rg.destination_dn_number = '${ring_group:value}')\r\n      AND sub_rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n  )\r\n),\r\n-- Ring group totals\r\nrg_totals AS (\r\n  SELECT\r\n    0 AS row_order_no,\r\n    MAX(rg.destination_dn_number) AS rg_dn,\r\n    MAX(rg_info.name) AS rg_name,\r\n    COUNT(DISTINCT rg.cdr_id) AS rg_received_count,\r\n    COUNT(DISTINCT\r\n      CASE\r\n        WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN rg.cdr_id\r\n      END\r\n    ) AS rg_answered_count\r\n  FROM public_cdroutput AS rg\r\n  INNER JOIN rg_info ON TRUE \r\n  LEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n    continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n    AND continued_in_cdr.creation_forward_reason = 'polling'\r\n  WHERE $__timeFilter(rg.cdr_started_at)\r\n    AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\n    AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n  GROUP BY rg.destination_dn_number -- Added GROUP BY for rg_totals\r\n),\r\n-- Ring group users statistics\r\nrg_users_stat AS (\r\n  SELECT\r\n    1 AS row_order_no,\r\n    MAX(rg.destination_dn_number) AS rg_dn,\r\n    MAX(rg_info.name) AS rg_name,\r\n    agent_polls.destination_dn_number AS agent_dn,\r\n    COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent_name,\r\n    COUNT(DISTINCT CASE WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN rg.cdr_id END) AS agent_answered_polls_count,\r\n    COUNT(agent_polls.cdr_id) AS agent_received_polls_count\r\n  FROM public_cdroutput AS rg\r\n  INNER JOIN rg_info ON TRUE -- This will cause issues if rg_info returns multiple rows. See note below.\r\n  INNER JOIN public_cdroutput AS agent_polls ON\r\n    agent_polls.call_history_id = rg.call_history_id\r\n    AND agent_polls.originating_cdr_id = rg.cdr_id\r\n    AND agent_polls.destination_dn_type = 'extension'\r\n    AND agent_polls.creation_method = 'route_to'\r\n    AND agent_polls.creation_forward_reason = 'polling'\r\n  WHERE $__timeFilter(rg.cdr_started_at)\r\n    AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\n    AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n  GROUP BY agent_polls.destination_dn_number, agent_polls.destination_dn_name, rg.destination_dn_number -- Added rg.destination_dn_number to GROUP BY\r\n)\r\nSELECT\r\n  rg.row_order_no,\r\n  CONCAT(CASE WHEN '${ring_group:value}' != 'All' THEN CONCAT(rg.rg_dn, ' ') ELSE '' END, rg.rg_name, ' [totals]') AS extension,\r\n  COALESCE(rg.rg_received_count, 0) AS calls_received,\r\n  COALESCE(rg.rg_received_count, 0) - COALESCE(rg.rg_answered_count, 0) AS calls_unanswered,\r\n  COALESCE(rg.rg_answered_count, 0) AS calls_answered,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS polls_received,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS polls_missed\r\nFROM rg_totals AS rg\r\nUNION ALL\r\nSELECT\r\n  u.row_order_no,\r\n  CONCAT(u.agent_dn, ' ', u.agent_name) AS extension,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS calls_received,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS calls_unanswered,\r\n  COALESCE(u.agent_answered_polls_count, 0) AS calls_answered,\r\n  COALESCE(u.agent_received_polls_count, 0) AS polls_received,\r\n  COALESCE(u.agent_received_polls_count, 0) - COALESCE(u.agent_answered_polls_count, 0) AS polls_missed\r\nFROM rg_users_stat AS u\r\nORDER BY row_order_no, extension;"
    }
   ]
  },
  {
   "title": "Eingegangene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Time series Graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n    STR_TO_DATE(DATE_FORMAT(rg.cdr_started_at, '%Y-%m-%d %H:00:00'), '%Y-%m-%d %H:%i:%s') AS time,\r\n    COUNT(DISTINCT rg.cdr_id) AS num_calls\r\nFROM public_cdroutput AS rg\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nGROUP BY 1\r\nORDER BY 1\r\n;"
    }
   ]
  },
  {
   "title": "Anrufstatistik nach Rufgruppenmitgliedern",
   "type": "barchart",
   "description": "This shows the number of answered calls per extension in the ring group.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  CONCAT(agent_polls.destination_dn_number, ' ', COALESCE(agent_polls.destination_dn_name, 'Unknown')) AS agent,\r\n  COUNT(DISTINCT agent_polls.main_call_history_id) AS agent_received_calls_count,\r\n  COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\r\n  COUNT(DISTINCT CASE WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN rg.cdr_id END) AS agent_answered_polls_count\r\nFROM public_cdroutput AS rg\r\nINNER JOIN public_cdroutput AS agent_polls ON\r\n  agent_polls.call_history_id = rg.call_history_id\r\n  AND agent_polls.originating_cdr_id = rg.cdr_id\r\n  AND agent_polls.destination_dn_type = 'extension'\r\n  AND agent_polls.creation_method = 'route_to'\r\n  AND agent_polls.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\n  AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\n  AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nGROUP BY agent\r\nORDER BY agent\r\n;"
    }
   ]
  }
 ]
}