{
 "title": "03. Warteschlangen (MySQL)",
 "description": "Queues Dashboard and Analytics",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": "WITH q AS (\n  SELECT\n    q.destination_dn_number AS dn_number,\n    COALESCE(q.destination_dn_name, 'Unknown') AS name,\n    ROW_NUMBER() OVER (PARTITION BY q.destination_dn_number ORDER BY q.cdr_started_at DESC) AS row_num\n  FROM public_cdroutput AS q\n  WHERE q.destination_dn_type = 'queue'\n  AND q.destination_dn_number IS NOT NULL\n  AND q.cdr_started_at >= NOW() - INTERVAL 365 day\n)\nSELECT\n  CONCAT(q.dn_number, ' ', q.name) AS __text,\n  q.dn_number AS __value\nFROM q\nWHERE q.row_num = 1\nORDER BY __value;"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ${queue:text}" } },
  {
   "title": "Eingegangene Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der eingegangenen Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  SUM(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMPDIFF(SECOND, continued_in_cdr.cdr_answered_at, continued_in_cdr.cdr_ended_at)\r\n    END\r\n  ) AS total_talking_time\r\nFROM public_cdroutput AS q\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Längste Anrufdauer",
   "type": "stat",
   "description": "Dauer des längsten Anrufs im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  MAX(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMPDIFF(SECOND, q.cdr_started_at, continued_in_cdr.cdr_ended_at)\r\n      ELSE TIMESTAMPDIFF(SECOND, q.cdr_started_at, q.cdr_ended_at)\r\n    END\r\n  ) AS duration\r\nFROM public_cdroutput AS q\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Ø Klingelzeit",
   "type": "stat",
   "description": "Durchschnittliche Wartezeit bis zur Annahme",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  AVG(TIMESTAMPDIFF(SECOND, q.cdr_started_at, q.cdr_ended_at)) AS duration\r\nFROM public_cdroutput AS q\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Anrufergebnis",
   "type": "piechart",
   "description": "Verteilung der Anrufergebnisse (angenommen, verpasst, etc.)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN COALESCE(continued_in_cdr.termination_reason, 'other')\r\n        ELSE COALESCE(CONCAT('not_answered__', q.termination_reason), 'other')\r\n    END\r\n    AS call_outcome,\r\n    COUNT(*) AS call_count\r\nFROM public_cdroutput AS q\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\nGROUP BY call_outcome\r\nORDER BY call_count DESC\r\n;"
    }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "% Calls Not Answered",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Rückrufe bearbeitet [auto]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  AVG(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMPDIFF(SECOND, continued_in_cdr.cdr_answered_at, continued_in_cdr.cdr_ended_at)\r\n    END\r\n  ) AS total_talking_time\r\nFROM public_cdroutput AS q\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  AVG(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMPDIFF(SECOND, q.cdr_started_at, continued_in_cdr.cdr_ended_at)\r\n      ELSE TIMESTAMPDIFF(SECOND, q.cdr_started_at, q.cdr_ended_at)\r\n    END\r\n  ) AS duration\r\nFROM public_cdroutput AS q\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Eingegangene / Angenommene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Zeitlicher Vergleich von eingegangenen und angenommenen Anrufen",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n    STR_TO_DATE(DATE_FORMAT(q.cdr_started_at, '%Y-%m-%d %H:00:00'), '%Y-%m-%d %H:%i:%s') AS call_time,\r\n    COUNT(DISTINCT q.cdr_id) AS total_calls,\r\n    COUNT(DISTINCT\r\n    CASE\r\n        WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN q.cdr_id\r\n    END\r\n    ) AS answered_calls\r\nFROM public_cdroutput AS q\r\nLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\nGROUP BY call_time\r\nORDER BY call_time\r\n;"
    }
   ]
  },
  {
   "title": "Warteschlangen-Statistik",
   "type": "table",
   "description": "Detaillierte Anrufstatistik der Warteschlange im Zeitraum",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- Queue info with last name\r\nWITH q_info AS (\r\n\tSELECT\r\n\t\tq.destination_dn_number AS dn_number,\r\n    CASE WHEN '${queue:value}' = 'All' THEN 'All queues' ELSE COALESCE(q.destination_dn_name, 'Unknown') END AS name\r\n\tFROM public_cdroutput AS q\r\n\tWHERE q.cdr_id = (\r\n\t\tSELECT\r\n\t\t\tMAX(q.cdr_id)\r\n\t\tFROM public_cdroutput AS q\r\n\t\tWHERE $__timeFilter(q.cdr_started_at)\r\n  \t  AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\n      AND q.destination_dn_type = 'queue'\r\n\t)\r\n),\r\n-- Queue totals\r\nq_totals AS (\r\n\tSELECT\r\n    0 AS row_order_no,\r\n\t\tMAX(q.destination_dn_number) AS q_dn,\r\n\t\tMAX(q_info.name) AS q_name,\r\n\t\tCOUNT(DISTINCT q.cdr_id) AS q_received_count,\r\n\t\tCOUNT(DISTINCT\r\n\t\t\tCASE\r\n\t\t\t\tWHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n\t\t\t\tTHEN q.cdr_id\r\n\t\t\tEND\r\n\t\t) AS q_answered_count,\r\n    COUNT(DISTINCT cbi.cdr_id) AS qcb_serviced_count\r\n\tFROM public_cdroutput AS q\r\n\tINNER JOIN q_info ON TRUE\r\n\tLEFT JOIN public_cdroutput AS continued_in_cdr ON\r\n\t\tcontinued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n\t\tAND continued_in_cdr.creation_forward_reason = 'polling'\r\n  LEFT JOIN public_cdroutput AS qcb ON\r\n    q.termination_reason = 'continued_in'\r\n    AND q.termination_reason_details = 'callback_requested'\r\n    AND qcb.cdr_id = q.continued_in_cdr_id\r\n    AND qcb.creation_forward_reason = 'callback_requested'\r\n    AND qcb.source_entity_type = 'queue'\r\n    AND qcb.destination_dn_number = 'QCB'\r\n    AND qcb.termination_reason = 'continued_in'\r\n  LEFT JOIN public_cdroutput AS cb ON\r\n    cb.cdr_id = qcb.continued_in_cdr_id\r\n    AND cb.source_dn_number = 'QCB'\r\n    AND cb.continued_in_cdr_id IS NOT NULL\r\n    AND cb.termination_reason_details = 'callback'\r\n  LEFT JOIN public_cdroutput AS cbi ON\r\n    cbi.cdr_id = cb.continued_in_cdr_id\r\n    AND cbi.creation_method = 'route_to'\r\n    AND cbi.cdr_answered_at IS NOT NULL\r\n\tWHERE $__timeFilter(q.cdr_started_at)\r\n    AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\n    AND q.destination_dn_type = 'queue'\r\n),\r\nqcb_user_stat AS (\r\n  SELECT\r\n    MAX(q.destination_dn_number) AS q_dn,\r\n    MAX(q_info.name) AS q_name,\r\n    cbi.source_dn_number AS agent_dn,\r\n    COALESCE(cbi.source_dn_name, 'Unknown') AS agent_name,\r\n    0 AS agent_answered_polls_count,\r\n    0 AS agent_received_polls_count,\r\n    COUNT(DISTINCT cbi.cdr_id) AS agent_qcb_serviced_count\r\n  FROM public_cdroutput AS q\r\n  INNER JOIN q_info ON TRUE\r\n  INNER JOIN public_cdroutput AS qcb ON\r\n    q.termination_reason = 'continued_in'\r\n    AND q.termination_reason_details = 'callback_requested'\r\n    AND qcb.cdr_id = q.continued_in_cdr_id\r\n    AND qcb.creation_forward_reason = 'callback_requested'\r\n    AND qcb.source_entity_type = 'queue'\r\n    AND qcb.destination_dn_number = 'QCB'\r\n    AND qcb.termination_reason = 'continued_in'\r\n  INNER JOIN public_cdroutput AS cb ON\r\n    cb.cdr_id = qcb.continued_in_cdr_id\r\n    AND cb.source_dn_number = 'QCB'\r\n    AND cb.continued_in_cdr_id IS NOT NULL\r\n    AND cb.termination_reason_details = 'callback'\r\n  INNER JOIN public_cdroutput AS cbi ON\r\n    cbi.cdr_id = cb.continued_in_cdr_id\r\n    AND cbi.creation_method = 'route_to'\r\n    AND cbi.cdr_answered_at IS NOT NULL\r\n    AND cbi.source_dn_type = 'extension'\r\n  WHERE $__timeFilter(q.cdr_started_at)\r\n    AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\n    AND q.destination_entity_type = 'queue'\r\n    AND q.termination_reason = 'continued_in'\r\n    AND q.termination_reason_details = 'callback_requested'\r\n  GROUP BY cbi.source_dn_number, cbi.source_dn_name\r\n),\r\n-- Queue agents statistics\r\nq_user_stat AS (\r\n  SELECT\r\n    MAX(q.destination_dn_number) AS q_dn,\r\n    MAX(q_info.name) AS q_name,\r\n    agent_polls.destination_dn_number AS agent_dn,\r\n    COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent_name,\r\n    COUNT(DISTINCT CASE WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN q.cdr_id END) AS agent_answered_polls_count,\r\n    COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\r\n    0 AS agent_qcb_serviced_count\r\n  FROM public_cdroutput AS q\r\n  INNER JOIN q_info ON TRUE\r\n  INNER JOIN public_cdroutput AS agent_polls ON\r\n    agent_polls.call_history_id = q.call_history_id\r\n    AND agent_polls.originating_cdr_id = q.cdr_id\r\n    AND agent_polls.destination_dn_type = 'extension'\r\n    AND agent_polls.creation_method = 'route_to'\r\n    AND agent_polls.creation_forward_reason = 'polling'\r\n  WHERE $__timeFilter(q.cdr_started_at)\r\n    AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\n    AND q.destination_dn_type = 'queue'\r\n  GROUP BY agent_polls.destination_dn_number, agent_polls.destination_dn_name\r\n)\r\nSELECT\r\n  q.row_order_no,\r\n  CONCAT(CASE WHEN '${queue:value}' != 'All' THEN CONCAT(q.q_dn, ' ') ELSE '' END, q.q_name, ' [totals]') AS extension,\r\n  COALESCE(q.q_received_count, 0) AS calls_received,\r\n  COALESCE(q.q_received_count, 0) - COALESCE(q.q_answered_count, 0) - COALESCE(q.qcb_serviced_count, 0) AS calls_unanswered,\r\n  COALESCE(q.q_answered_count, 0) + COALESCE(q.qcb_serviced_count, 0) AS calls_answered,\r\n  COALESCE(q.qcb_serviced_count, 0) AS qcb_serviced,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS polls_received,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS polls_missed\r\nFROM q_totals AS q\r\nUNION ALL\r\nSELECT\r\n  u.row_order_no,\r\n  CONCAT(u.agent_dn, ' ', u.agent_name) AS extension,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS calls_received,\r\n  CAST(NULL AS UNSIGNED INTEGER) AS calls_unanswered,\r\n  COALESCE(u.agent_answered_polls_count, 0) + COALESCE(u.agent_qcb_serviced_count, 0) AS calls_answered,\r\n  COALESCE(u.agent_qcb_serviced_count, 0) AS qcb_serviced,\r\n  COALESCE(u.agent_received_polls_count, 0) AS polls_received,\r\n  COALESCE(u.agent_received_polls_count, 0) - COALESCE(u.agent_answered_polls_count, 0) AS polls_missed\r\nFROM (\r\n  SELECT\r\n    1 AS row_order_no,\r\n    MAX(u.q_dn) AS q_dn,\r\n    MAX(u.q_name) AS q_name,\r\n    u.agent_dn AS agent_dn,\r\n    u.agent_name AS agent_name,\r\n    SUM(u.agent_answered_polls_count) AS agent_answered_polls_count,\r\n    SUM(u.agent_received_polls_count) AS agent_received_polls_count,\r\n    SUM(u.agent_qcb_serviced_count) AS agent_qcb_serviced_count\r\n  FROM (\r\n    SELECT *\r\n    FROM q_user_stat AS u\r\n    UNION ALL\r\n    SELECT *\r\n    FROM qcb_user_stat AS cb\r\n  ) AS u\r\n  GROUP BY u.agent_dn, u.agent_name\r\n) AS u\r\nORDER BY row_order_no, extension\r\n;"
    }
   ]
  },
  {
   "title": "Eingegangene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Time series Graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n    STR_TO_DATE(DATE_FORMAT(q.cdr_started_at, '%Y-%m-%d %H:00:00'), '%Y-%m-%d %H:%i:%s') AS time_bucket,\r\n    COUNT(DISTINCT q.cdr_id) AS num_calls\r\nFROM public_cdroutput AS q\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\nGROUP BY time_bucket\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Anrufstatistik nach Agenten",
   "type": "barchart",
   "description": "This shows the number of answered calls per extension in the queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "SELECT\r\n  CONCAT(agent_polls.destination_dn_number, ' ', COALESCE(agent_polls.destination_dn_name, 'Unknown')) AS agent,\r\n  COUNT(DISTINCT agent_polls.main_call_history_id) AS agent_received_calls_count,\r\n  COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\r\n  COUNT(DISTINCT CASE WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN q.cdr_id END) AS agent_answered_polls_count\r\nFROM public_cdroutput AS q\r\nINNER JOIN public_cdroutput AS agent_polls ON\r\n  agent_polls.call_history_id = q.call_history_id\r\n  AND agent_polls.originating_cdr_id = q.cdr_id\r\n  AND agent_polls.destination_dn_type = 'extension'\r\n  AND agent_polls.creation_method = 'route_to'\r\n  AND agent_polls.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\n  AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\n  AND q.destination_dn_type = 'queue'\r\nGROUP BY agent\r\nORDER BY agent\r\n;"
    }
   ]
  }
 ]
}