{
 "title": "06. Eingehende Anrufe (MySQL)",
 "description": "A visual showing all Inbound Calls ",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Eingehende Anrufe" } },
  {
   "title": "Eingegangene Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der eingegangenen Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- ----------------------------\r\n-- Inbound answered connections\r\n-- ----------------------------\r\nWITH inbound_connections AS (\r\n\t-- ------\r\n\t-- Source\r\n\t-- ------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, coalesce(c.cdr_answered_at, c.cdr_ended_at)) AS ringing_duration,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN public_cdroutput AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t-- -----------\r\n\t-- Destination\r\n\t-- -----------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, coalesce(c.cdr_answered_at, c.cdr_ended_at)) AS ringing_duration,\r\n\t\tcoalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tCOUNT(DISTINCT c.main_call_history_id) AS calls_received,\r\n\tCOUNT(DISTINCT CASE WHEN c.talking_duration > 0 THEN c.main_call_history_id END) AS calls_answered,\r\n\tCOUNT(DISTINCT CASE WHEN c.talking_duration > 0 THEN c.main_call_history_id END) * 100.0 / \r\n\t\tCASE WHEN COUNT(DISTINCT c.main_call_history_id) = 0 THEN 1 ELSE COUNT(DISTINCT c.main_call_history_id) END AS calls_answered_percent,\r\n\tCOUNT(DISTINCT c.main_call_history_id) - COUNT(DISTINCT CASE WHEN c.talking_duration > 0 THEN c.main_call_history_id END) AS calls_unanswered,\r\n\tSUM(c.talking_duration) AS talking_duration,\r\n\tSUM(c.talking_duration) / CASE WHEN COUNT(DISTINCT c.main_call_history_id) = 0 THEN 1 ELSE COUNT(DISTINCT c.main_call_history_id) END AS avg_talking_duration,\r\n\tSUM(c.duration) / CASE WHEN COUNT(DISTINCT c.main_call_history_id) = 0 THEN 1 ELSE COUNT(DISTINCT c.main_call_history_id) END AS avg_duration,\r\n\tSUM(c.duration) AS duration\r\nFROM inbound_connections AS c\r\n;"
    }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Total Call Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Anrufe nach DID",
   "type": "piechart",
   "description": "Verteilung der Anrufe auf die verschiedenen DID-Nummern",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- ----------------------------\r\n-- Inbound answered connections\r\n-- ----------------------------\r\nWITH inbound_connections AS (\r\n\t-- ------\r\n\t-- Source\r\n\t-- ------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\tcoalesce(c.source_participant_trunk_did, 'Unknown') AS did\r\n\tFROM public_cdroutput AS c\r\n\tLEFT JOIN public_cdroutput AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t-- -----------\r\n\t-- Destination\r\n\t-- -----------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\tcoalesce(c.destination_participant_trunk_did, 'Unknown') AS did\r\n\tFROM public_cdroutput AS c\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tc.did,\r\n\tcount(DISTINCT c.main_call_history_id) AS calls\r\nFROM inbound_connections AS c\r\nGROUP BY c.did\r\nORDER BY calls DESC\r\n;"
    }
   ]
  },
  {
   "title": "Eingehende Anrufe (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf der eingehenden Anrufe",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -------------------\r\n-- Inbound connections\r\n-- -------------------\r\nWITH inbound_connections AS (\r\n\t-- ------\r\n\t-- Source\r\n\t-- ------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at\r\n\tFROM public_cdroutput AS c\r\n\tLEFT JOIN public_cdroutput AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY c.main_call_history_id, participant_id\r\n\tUNION ALL\r\n\t-- -----------\r\n\t-- Destination\r\n\t-- -----------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY c.main_call_history_id, participant_id\r\n)\r\nSELECT\r\n\tSTR_TO_DATE(DATE_FORMAT(i.started_at, '%Y-%m-%d %H:00:00'), '%Y-%m-%d %H:%i:%s') AS time_bucket,\r\n\tCOUNT(DISTINCT i.participant_id) AS calls\r\nFROM inbound_connections AS i\r\nGROUP BY time_bucket\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Top Durchwahlen",
   "type": "barchart",
   "description": "Die Durchwahlen mit den meisten eingehenden Anrufen",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -------------------\r\n-- Inbound connections\r\n-- -------------------\r\nWITH inbound_connections AS (\r\n\t-- ------\r\n\t-- Source\r\n\t-- ------\r\n\tSELECT\r\n\t\t-- c.main_call_history_id,\r\n    c.destination_participant_id AS extension_participant_id,\r\n\t\tmax(CASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\tEND) AS extension\r\n\tFROM public_cdroutput AS c\r\n\tLEFT JOIN public_cdroutput AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY extension_participant_id\r\n\tUNION ALL\r\n\t-- -----------\r\n\t-- Destination\r\n\t-- -----------\r\n\tSELECT\r\n\t\t-- c.main_call_history_id,\r\n    c.source_participant_id AS extension_participant_id,\r\n\t\tmax(CASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tEND) AS extension\r\n\tFROM public_cdroutput AS c\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY extension_participant_id\r\n)\r\nSELECT\r\n\ti.extension,\r\n\tcount(DISTINCT i.extension_participant_id) AS calls\r\nFROM inbound_connections AS i\r\nGROUP BY extension\r\nORDER BY calls DESC\r\nLIMIT 10\r\n;"
    }
   ]
  },
  {
   "title": "Liste eingehender Anrufe",
   "type": "table",
   "description": "Detaillierte Liste aller eingehenden Anrufe der häufigsten Anrufer",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -------------------\r\n-- Inbound connections\r\n-- -------------------\r\nWITH inbound_connections AS (\r\n\t-- ------\r\n\t-- Source\r\n\t-- ------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tcoalesce(c.source_participant_trunk_did, 'Unknown') AS did,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, coalesce(c.cdr_answered_at, c.cdr_ended_at)) AS ringing_duration,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN public_cdroutput AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t-- -----------\r\n\t-- Destination\r\n\t-- -----------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tcoalesce(c.destination_participant_trunk_did, 'Unknown') AS did,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\t\tELSE CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tTIMESTAMPDIFF(SECOND, c.cdr_started_at, coalesce(c.cdr_answered_at, c.cdr_ended_at)) AS ringing_duration,\r\n\t\tcoalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t-- AND c.cdr_answered_at IS NOT NULL\r\n),\r\nstat AS (\r\n\tSELECT\r\n\t\tROW_NUMBER() OVER(ORDER BY c.started_at DESC) AS id1,\r\n\t\tCASE WHEN (ROW_NUMBER() OVER(PARTITION BY c.main_call_history_id ORDER BY c.started_at DESC) - 1) > 0 THEN 1 ELSE 0 END AS id2,\r\n\t\tc.*\r\n\tFROM inbound_connections AS c\r\n)\r\nSELECT\r\n\t(c.id1 - SUM(c.id2) OVER(ORDER BY c.started_at DESC)) % 2 AS gen_call_id,\r\n\t-- c.main_call_history_id,\r\n\tc.source_participant,\r\n\tc.did,\r\n\tc.destination_participant,\r\n\tc.started_at,\r\n\tc.answered_at,\r\n\tc.ended_at,\r\n\tc.duration,\r\n\tc.ringing_duration,\r\n\tc.talking_duration,\r\n\tc.bill_cost\r\nFROM stat AS c\r\nORDER BY c.started_at DESC\r\n;"
    }
   ]
  }
 ]
}