{
 "title": "09. Outbound Call Legs By Cost, (Participants & Extensions) (MySSQL)",
 "description": "Outbound Call Legs By Cost, (Participants & Extensions)\nPurpose: Detect highest cost calls and customers. \n",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "bill_cost_treshhold", "label": "Bill Cost per connection >=", "query": "0.00" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 3CX – Ausgehende Anrufe nach Kosten"
   }
  },
  {
   "title": "Übersicht",
   "type": "row",
   "description": "Überblick über die hochwertigsten ausgehenden Anrufe",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Angenommene Verbindungen",
   "type": "bargauge",
   "description": "Anzahl der Verbindungen über und unter dem Kostenschwellwert",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n)\r\nSELECT\r\n  'high value calls ratio' AS text,\r\n  count(*) AS total_connections,\r\n  count(CASE WHEN o.bill_cost >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN 1 END) AS high_value_connections,\r\n  count(CASE WHEN o.bill_cost < CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN 1 END) AS no_value_connections\r\nFROM outbound_stat AS o\r\n;"
    }
   ]
  },
  {
   "title": "% über Schwellwert",
   "type": "gauge",
   "description": "Prozentualer Anteil der Verbindungen über dem Kostenschwellwert",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n)\r\nSELECT\r\n  -- High value connections\r\n  coalesce(count(CASE WHEN o.bill_cost >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN 1 END), 0)\r\n  * 100.0\r\n  -- All connections\r\n  / CASE WHEN count(*) = 0 THEN 1 ELSE count(*) END\r\nFROM outbound_stat AS o\r\n;"
    }
   ]
  },
  {
   "title": "Ø Kosten",
   "type": "stat",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n\t\tsum(o.bill_cost) AS bill_cost,\r\n    sum(o.talking_duration) AS talking_duration\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n)\r\nSELECT\r\n  round(avg(CASE WHEN o.bill_cost >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN o.bill_cost END), 2) AS high_value_avg_bill_cost\r\nFROM outbound_stat AS o\r\n;"
    }
   ]
  },
  {
   "title": "Gesamtkosten",
   "type": "stat",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n\t\tsum(o.bill_cost) AS bill_cost,\r\n    sum(o.talking_duration) AS talking_duration\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n)\r\nSELECT\r\n  sum(CASE WHEN o.bill_cost >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN o.bill_cost END) AS high_value_total_bill_cost\r\nFROM outbound_stat AS o\r\n;"
    }
   ]
  },
  {
   "title": "Ø Gesprächszeit",
   "type": "stat",
   "description": "for Over Threshold Connections.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n\t\tsum(o.bill_cost) AS bill_cost,\r\n    sum(o.talking_duration) AS talking_duration\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n)\r\nSELECT\r\n  avg(CASE WHEN o.bill_cost >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN o.talking_duration END) AS high_value_avg_duration\r\nFROM outbound_stat AS o\r\n;"
    }
   ]
  },
  {
   "title": "Gesamte Gesprächszeit",
   "type": "stat",
   "description": "of All Connections Over Threshold",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n\t\tsum(o.bill_cost) AS bill_cost,\r\n    sum(o.talking_duration) AS talking_duration\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n)\r\nSELECT\r\n  sum(CASE WHEN o.bill_cost >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2)) THEN o.talking_duration END) AS high_value_total_duration\r\nFROM outbound_stat AS o\r\n;"
    }
   ]
  },
  {
   "title": "Gesprächszeit-Verteilung",
   "type": "barchart",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n    sum(o.duration) AS duration,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n  HAVING sum(o.bill_cost) >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2))\r\n)\r\nSELECT\r\n  0 AS row_order,\r\n  '< 5 min' AS duration_type,\r\n  count(CASE WHEN o.duration < 300 THEN 1 END) AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  1 AS row_order,\r\n  '5-10 min' AS duration_type,\r\n  count(CASE WHEN o.duration BETWEEN 300 AND 599 THEN 1 END) AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  2 AS row_order,\r\n  '10-15 min' AS duration_type,\r\n  count(CASE WHEN o.duration BETWEEN 600 AND 899 THEN 1 END) AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  3 AS row_order,\r\n  '15-20 min' AS duration_type,\r\n  count(CASE WHEN o.duration BETWEEN 900 AND 1199 THEN 1 END) AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  4 AS row_order,\r\n  '20+ min' AS duration_type,\r\n  count(CASE WHEN o.duration >= 1200 THEN 1 END) AS connections\r\nFROM outbound_stat AS o\r\nORDER BY row_order\r\n;"
    }
   ]
  },
  {
   "title": "Kosten-Verteilung",
   "type": "barchart",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n    sum(o.duration) AS duration,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n  HAVING sum(o.bill_cost) >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2))\r\n)\r\nSELECT\r\n  0 AS row_order,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN '0.00 - 1.00'\r\n    ELSE CONCAT(CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63,2)), 2) AS CHAR), ' - ', CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) * 2, 2) AS CHAR))\r\n  END AS cost_type,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN count(CASE WHEN o.bill_cost <= 1.00 THEN 1 END)\r\n    ELSE count(CASE WHEN o.bill_cost >= ${bill_cost_treshhold} AND o.bill_cost <= ${bill_cost_treshhold} * 2 THEN 1 END)\r\n  END AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  1 AS row_order,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN '1.00 - 5.00'\r\n    ELSE CONCAT(CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63,2)) * 2, 2) AS CHAR), ' - ', CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) * 3, 2) AS CHAR))\r\n  END AS cost_type,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN count(CASE WHEN o.bill_cost > 1.00 AND o.bill_cost <= 5.00 THEN 1 END)\r\n    ELSE count(CASE WHEN o.bill_cost > ${bill_cost_treshhold} * 2 AND o.bill_cost <= ${bill_cost_treshhold} * 3 THEN 1 END)\r\n  END AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  2 AS row_order,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN '5.00 - 10.00'\r\n    ELSE CONCAT(CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63,2)) * 3, 2) AS CHAR), ' - ', CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) * 4, 2) AS CHAR))\r\n  END AS cost_type,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN count(CASE WHEN o.bill_cost > 5.00 AND o.bill_cost <= 10.00 THEN 1 END)\r\n    ELSE count(CASE WHEN o.bill_cost > ${bill_cost_treshhold} * 3 AND o.bill_cost <= ${bill_cost_treshhold} * 4 THEN 1 END)\r\n  END AS connections\r\nFROM outbound_stat AS o\r\nUNION ALL\r\nSELECT\r\n  3 AS row_order,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN '10.00 +'\r\n    ELSE CONCAT(CAST(ROUND(CAST(${bill_cost_treshhold} AS DECIMAL(63,2)) * 4, 2) AS CHAR), ' +')\r\n  END AS cost_type,\r\n  CASE\r\n    WHEN CAST(${bill_cost_treshhold} AS DECIMAL(63, 2)) = 0\r\n      THEN count(CASE WHEN o.bill_cost > 10.00 THEN 1 END)\r\n    ELSE count(CASE WHEN o.bill_cost > ${bill_cost_treshhold} * 4 THEN 1 END)\r\n  END AS connections\r\nFROM outbound_stat AS o\r\nORDER BY row_order\r\n;\r\n"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Top Ziel-Teilnehmer",
   "type": "barchart",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n    max(CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))) AS consumer,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n    max(CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))) AS consumer,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n    max(o.consumer) AS consumer,\r\n\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n  HAVING sum(o.bill_cost) >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2))\r\n)\r\nSELECT\r\n  o.consumer,\r\n  count(1) AS high_value_connections\r\nFROM outbound_stat AS o\r\nGROUP BY o.consumer\r\nORDER BY high_value_connections DESC\r\nLIMIT 10\r\n;"
    }
   ]
  },
  {
   "title": "Top Ziel-Teilnehmer",
   "type": "table",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n    max(CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))) AS consumer,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n    max(CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))) AS consumer,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n    max(o.consumer) AS consumer,\r\n\t\tsum(o.talking_duration) AS talking_duration,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n  HAVING sum(o.bill_cost) >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2))\r\n)\r\nSELECT\r\n  o.consumer,\r\n  count(*) AS connections,\r\n  sum(o.talking_duration) AS talking_duration,\r\n  sum(o.bill_cost) AS bill_cost\r\nFROM outbound_stat AS o\r\nGROUP BY o.consumer\r\nORDER BY sum(o.bill_cost) DESC\r\n;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top Durchwahlen über Kostenschwellwert",
   "type": "barchart",
   "description": "Durchwahlen mit den meisten Anrufen über dem Kostenschwellwert",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n\t$__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id,\r\n    sum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n  HAVING sum(o.bill_cost) >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2))\r\n)\r\nSELECT\r\n\tCASE\r\n\t\tWHEN c.source_entity_type = 'extension'\r\n      THEN CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tELSE\r\n      CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\tEND AS extension,\r\n\tsum(\r\n    round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)\r\n\t\t+\r\n    round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)\r\n\t) AS bill_cost,\r\n\tCOUNT(1) AS high_value_connections\r\nFROM public_cdroutput AS c\r\nLEFT JOIN outbound_stat AS os ON\r\n  os.participant_id = c.source_participant_id\r\nLEFT JOIN outbound_stat AS od ON\r\n  od.participant_id = c.destination_participant_id\r\nINNER JOIN public_cdrbilling AS b ON\r\n  b.cdr_id = c.cdr_id\r\nWHERE\r\n$__timeFilter(c.cdr_started_at)\r\nAND\r\n  (\r\n    c.destination_entity_type = 'external_line' AND c.destination_participant_is_incoming = FALSE AND c.source_entity_type = 'extension'\r\n    OR\r\n    c.source_entity_type = 'external_line' AND c.source_participant_is_incoming = FALSE AND c.destination_entity_type = 'extension'\r\n  )\r\nAND c.cdr_answered_at IS NOT NULL\r\nAND (os.participant_id IS NOT NULL OR od.participant_id IS NOT NULL)\r\nGROUP BY\r\n\tCASE\r\n\t\tWHEN c.source_entity_type = 'extension'\r\n      THEN CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n\t\tELSE\r\n      CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n\tEND\r\nORDER BY bill_cost DESC\r\nLIMIT 10\r\n;"
    }
   ]
  },
  {
   "title": "Teuerste Anrufe",
   "type": "table",
   "description": "of all Connections Over Threshold.",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 32 },
   "targets": [
    {
     "dataset": "panagianbo",
     "rawSql": "-- -----------------------------\r\n-- Outbound answered connections\r\n-- -----------------------------\r\nWITH outbound_connections AS (\r\n  -- -----------\r\n  -- Destination\r\n  -- -----------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n  $__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  -- ------\r\n  -- Source\r\n  -- ------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tTIMESTAMPDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE\r\n  $__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = FALSE\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n    o.participant_id\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n  HAVING sum(o.bill_cost) >= CAST(NULLIF('${bill_cost_treshhold}', '') AS DECIMAL(63, 2))\r\n)\r\nSELECT\r\n  c.main_call_history_id,\r\n  c.cdr_started_at AS started_at,\r\n  c.cdr_answered_at AS answered_at,\r\n  c.cdr_ended_at AS ended_at,\r\n  CASE\r\n    WHEN c.source_entity_type = 'external_line'\r\n      THEN CONCAT(c.source_participant_phone_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n    ELSE CONCAT(c.source_dn_number, ' ', coalesce(c.source_dn_name, 'Unknown'))\r\n  END AS source_participant,\r\n  CASE\r\n    WHEN c.destination_entity_type = 'external_line'\r\n      THEN CONCAT(c.destination_participant_phone_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n    ELSE CONCAT(c.destination_dn_number, ' ', coalesce(c.destination_dn_name, 'Unknown'))\r\n  END AS destination_participant,\r\n  CASE\r\n  \tWHEN os.participant_id IS NOT NULL AND c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue')\r\n      THEN coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)\r\n  \tELSE 0\r\n  END AS source_talking_duration,\r\n  CASE\r\n  \tWHEN od.participant_id IS NOT NULL\r\n  \t  THEN coalesce(TIMESTAMPDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)\r\n  \tELSE 0\r\n  END AS destination_talking_duration,\r\n  CASE\r\n    WHEN os.participant_id IS NOT NULL\r\n      THEN coalesce(b.source_bill_code, 'Unknown')\r\n    ELSE ''\r\n  END AS source_bill_code,\r\n  CASE\r\n    WHEN od.participant_id IS NOT NULL\r\n      THEN coalesce(b.destination_bill_code, 'Unknown')\r\n    ELSE ''\r\n  END AS destination_bill_code,\r\n  CASE\r\n    WHEN os.participant_id IS NOT NULL\r\n      THEN coalesce(b.source_bill_rate_name, 'Unknown')\r\n    ELSE ''\r\n  END AS source_bill_rate_name,\r\n  CASE\r\n    WHEN od.participant_id IS NOT NULL\r\n      THEN coalesce(b.destination_bill_rate_name, 'Unknown')\r\n    ELSE ''\r\n  END AS destination_bill_rate_name,\r\n  CASE\r\n    WHEN os.participant_id IS NOT NULL\r\n      THEN coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00)\t-- Changed 'Unknown' to 0.00\r\n    ELSE 0.00\r\n  END AS source_bill_rate,\r\n  CASE\r\n    WHEN od.participant_id IS NOT NULL\r\n      THEN coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00)\t-- Changed 'Unknown' to 0.00\r\n    ELSE 0.00\r\n  END AS destination_bill_rate,\r\n  CASE\r\n    WHEN os.participant_id IS NOT NULL\r\n  \t  THEN round(coalesce(CAST(b.source_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.source_bill_duration) * 1000000 + MICROSECOND(b.source_bill_duration)) / 60000000, 0.00), 2)\r\n  \tELSE 0.00\r\n  END AS source_bill_cost,\r\n  CASE\r\n    WHEN od.participant_id IS NOT NULL\r\n  \t  THEN round(coalesce(CAST(b.destination_bill_rate AS DECIMAL(63, 2)), 0.00) * coalesce((TIME_TO_SEC(b.destination_bill_duration) * 1000000 + MICROSECOND(b.destination_bill_duration)) / 60000000, 0.00), 2)\r\n  \tELSE 0.00\r\n  END AS destination_bill_cost\r\nFROM public_cdroutput AS c\r\nLEFT JOIN outbound_stat AS os ON\r\n  os.participant_id = c.source_participant_id\r\nLEFT JOIN outbound_stat AS od ON\r\n  od.participant_id = c.destination_participant_id\r\nLEFT JOIN public_cdrbilling AS b ON\r\n  b.cdr_id = c.cdr_id\r\nWHERE\r\n$__timeFilter(c.cdr_started_at)\r\nAND\r\n  (\r\n    c.destination_entity_type = 'external_line' AND c.destination_participant_is_incoming = FALSE\r\n    OR\r\n    c.source_entity_type = 'external_line' AND c.source_participant_is_incoming = FALSE\r\n  )\r\nAND c.cdr_answered_at IS NOT NULL\r\nAND (os.participant_id IS NOT NULL OR od.participant_id IS NOT NULL)\r\nORDER BY answered_at DESC\r\n;"
    }
   ]
  }
 ]
}