{
 "title": "08. Eingehend vs. Ausgehend Analyse (MSSQL)",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Eingehend vs. Ausgehend Verkehrsanalyse"
   }
  },
  {
   "title": "Gesamte Anrufe",
   "type": "stat",
   "description": "Gesamtzahl aller Anrufe (ein- und ausgehend)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "-------------------------------\r\n-- Inbound answered connections\r\n-------------------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.source_participant_id AS participant_id,\r\n    min(c.cdr_started_at) AS started_at,\r\n\t\tsum(DATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = 1\r\n\tAND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY c.source_participant_id\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.destination_participant_id AS participant_id,\r\n    min(c.cdr_started_at) AS started_at,\r\n\t\tsum(DATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming = 1\r\n\tAND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY c.destination_participant_id\r\n),\r\n--------------------------------\r\n-- Outbound answered connections\r\n--------------------------------\r\noutbound_connections AS (\r\n  --------------\r\n  -- Destination\r\n  --------------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tDATEDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(\r\n\t\t\tround(coalesce(CAST(b.destination_bill_rate AS numeric(38, 2)), 0.00) * coalesce(DATEDIFF(MICROSECOND, 0, CAST(b.destination_bill_duration AS TIME)) / 60000000.00, 0.00), 2)\r\n    ) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = 0\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  ---------\r\n  -- Source\r\n  ---------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n\t\tDATEDIFF(SECOND, min(c.cdr_started_at), max(c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(\r\n\t\t\tround(coalesce(CAST(b.source_bill_rate AS numeric(38, 2)), 0.00) * coalesce(DATEDIFF(MICROSECOND, 0, CAST(b.source_bill_duration AS TIME)) / 60000000.00, 0.00), 2)\r\n    ) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = 0\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\n-- Inbound statistics\r\ninbound_stat AS (\r\n\tSELECT\r\n\t\t0 AS direction_id,\r\n\t\t'in' AS direction,\r\n\t\tDATEADD(HOUR, DATEDIFF(HOUR, 0, i.started_at), 0) AS time_bucket,\r\n\t\tcount(DISTINCT i.participant_id) AS connections_count,\r\n\t\tsum(i.duration) AS duration,\r\n\t\tsum(i.talking_duration) AS talking_duration,\r\n\t\tsum(i.bill_cost) AS bill_cost\r\n\tFROM inbound_connections AS i\r\n\tGROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, i.started_at), 0)\r\n),\r\n-- Outbound statistics\r\noutbound_stat AS (\r\n\tSELECT\r\n\t\t1 AS direction_id,\r\n\t\t'out' AS direction,\r\n\t\tDATEADD(HOUR, DATEDIFF(HOUR, 0, o.started_at), 0) AS time_bucket,\r\n\t\tcount(DISTINCT o.participant_id) AS connections_count,\r\n\t\tsum(o.duration) AS duration,\r\n\t\tsum(o.talking_duration) AS talking_duration,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY DATEADD(HOUR, DATEDIFF(HOUR, 0, o.started_at), 0)\r\n)\r\nSELECT\r\n\tcoalesce(i.time_bucket, o.time_bucket) AS time_bucket,\r\n\tcoalesce(i.connections_count, 0) + coalesce(o.connections_count, 0) AS connections_count,\r\n\tcoalesce(i.connections_count, 0) AS inbound_connections_count,\r\n\tcoalesce(i.duration, 0) AS inbound_duration,\r\n\tcoalesce(i.talking_duration, 0) AS inbound_talking_duration,\r\n\tcoalesce(i.bill_cost, 0.00) AS inbound_bill_cost,\r\n\tcoalesce(o.connections_count, 0) AS outbound_connections_count,\r\n\tcoalesce(o.duration, 0) AS outbound_duration,\r\n\tcoalesce(o.talking_duration, 0) AS outbound_talking_duration,\r\n\tcoalesce(o.bill_cost, 0.00) AS outbound_bill_cost\r\nFROM inbound_stat AS i\r\nFULL JOIN outbound_stat AS o ON\r\n\to.time_bucket = i.time_bucket\r\nORDER BY coalesce(i.time_bucket, o.time_bucket)\r\n;"
    }
   ]
  },
  {
   "title": "Angenommene Eingehende",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Eingehend Dauer",
   "type": "stat",
   "description": "Gesamtdauer aller eingehenden Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Eingehend Gesprächsdauer",
   "type": "stat",
   "description": "Gesamte Gesprächszeit aller eingehenden Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Angenommene Ausgehende",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Ausgehend Dauer",
   "type": "stat",
   "description": "Gesamtdauer aller ausgehenden Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Ausgehend Gesprächsdauer",
   "type": "stat",
   "description": "Gesamte Gesprächszeit aller ausgehenden Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Ausgehend Kosten",
   "type": "stat",
   "description": "Gesamtkosten der ausgehenden Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Anrufe nach Richtung",
   "type": "barchart",
   "description": "Vergleich von eingehenden und ausgehenden Anrufen",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Eingehend Anrufdauer",
   "type": "piechart",
   "description": "Verteilung der eingehenden Anrufe nach Dauer",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "-------------------------------\r\n-- Inbound answered connections\r\n-------------------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.source_participant_id AS participant_id,\r\n    min(c.cdr_started_at) AS started_at,\r\n\t\tsum(DATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = 1\r\n\tAND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY c.source_participant_id\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.destination_participant_id AS participant_id,\r\n    min(c.cdr_started_at) AS started_at,\r\n\t\tsum(DATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming = 1\r\n\tAND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY c.destination_participant_id\r\n),\r\ninbound_stat AS (\r\n\tSELECT\r\n\t\t0 AS direction_id,\r\n\t\t'in' AS direction,\r\n\t\tmin(i.started_at) AS started_at,\r\n\t\tsum(i.duration) AS duration,\r\n\t\tsum(i.talking_duration) AS talking_duration,\r\n\t\tsum(i.bill_cost) AS bill_cost\r\n\tFROM inbound_connections AS i\r\n\tGROUP BY i.participant_id\r\n),\r\ninbound_counts AS (\r\n\tSELECT\r\n\t\tcount(*) AS total_calls,\r\n\t\tcount(CASE WHEN i.duration < 60 THEN 1 END) AS less_than_1min,\r\n\t\tcount(CASE WHEN i.duration BETWEEN 60 AND 180 THEN 1 END) AS between_1min_and_3mins,\r\n\t\tcount(CASE WHEN i.duration > 180 THEN 1 END) AS more_than_3mins\r\n\tFROM inbound_stat AS i\r\n)\r\nSELECT\r\n\t*,\r\n\t100.00 / (CASE WHEN i.total_calls IS NULL OR i.total_calls = 0 THEN 1 ELSE i.total_calls END) * coalesce(i.less_than_1min, 0) AS less_than_1min_perc,\r\n\t100.00 / (CASE WHEN i.total_calls IS NULL OR i.total_calls = 0 THEN 1 ELSE i.total_calls END) * coalesce(i.between_1min_and_3mins, 0) AS between_1min_and_3mins_perc,\r\n\t100.00 / (CASE WHEN i.total_calls IS NULL OR i.total_calls = 0 THEN 1 ELSE i.total_calls END) * coalesce(i.more_than_3mins, 0) AS more_than_3mins_perc\r\nFROM inbound_counts AS i\r\n;"
    }
   ]
  },
  {
   "title": "Ausgehend Anrufdauer",
   "type": "piechart",
   "description": "Verteilung der ausgehenden Anrufe nach Dauer",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "--------------------------------\r\n-- Outbound answered connections\r\n--------------------------------\r\nWITH outbound_connections AS (\r\n  --------------\r\n  -- Destination\r\n  --------------\r\n  SELECT\r\n    c.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n    sum(DATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at)) AS duration,\r\n\t\tsum(coalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0)) AS talking_duration,\r\n    sum(\r\n      round(coalesce(CAST(b.destination_bill_rate AS numeric(38, 2)), 0.00) * coalesce(DATEDIFF(MICROSECOND, 0, CAST(b.destination_bill_duration AS TIME)) / 60000000.00, 0.00), 2)\r\n    ) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = 0\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.destination_participant_id\r\n  UNION ALL\r\n  ---------\r\n  -- Source\r\n  ---------\r\n  SELECT\r\n    c.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at,\r\n    sum(DATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at)) AS duration,\r\n\t\tsum(CASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END) AS talking_duration,\r\n    sum(\r\n      round(coalesce(CAST(b.source_bill_rate AS numeric(38, 2)), 0.00) * coalesce(DATEDIFF(MICROSECOND, 0, CAST(b.source_bill_duration AS TIME)) / 60000000.00, 0.00), 2)\r\n    ) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = 0\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY c.source_participant_id\r\n),\r\noutbound_stat AS (\r\n\tSELECT\r\n\t\t1 AS direction_id,\r\n\t\t'out' AS direction,\r\n\t\tmin(o.started_at) AS started_at,\r\n\t\tsum(o.duration) AS duration,\r\n\t\tsum(o.talking_duration) AS talking_duration,\r\n\t\tsum(o.bill_cost) AS bill_cost\r\n\tFROM outbound_connections AS o\r\n\tGROUP BY o.participant_id\r\n),\r\noutbound_counts AS (\r\n\tSELECT\r\n\t\tcount(*) AS total_calls,\r\n\t\tcount(CASE WHEN o.duration < 60 THEN 1 END) AS less_than_1min,\r\n\t\tcount(CASE WHEN o.duration BETWEEN 60 AND 180 THEN 1 END) AS between_1min_and_3mins,\r\n\t\tcount(CASE WHEN o.duration > 180 THEN 1 END) AS more_than_3mins,\r\n\t\tsum(CASE WHEN o.bill_cost < 1.00 THEN 1 END) AS cost_less_than_1,\r\n\t\tsum(CASE WHEN o.bill_cost BETWEEN 1.00 AND 2.00 THEN 1 END) AS cost_between_1_and_2,\r\n\t\tsum(CASE WHEN o.bill_cost > 2.00 THEN 1 END) AS cost_more_than_2\r\n\tFROM outbound_stat AS o\r\n)\r\nSELECT\r\n\t*,\r\n\t100.00 / (CASE WHEN o.total_calls IS NULL OR o.total_calls = 0 THEN 1 ELSE o.total_calls END) * coalesce(o.less_than_1min, 0) AS less_than_1min_perc,\r\n\t100.00 / (CASE WHEN o.total_calls IS NULL OR o.total_calls = 0 THEN 1 ELSE o.total_calls END) * coalesce(o.between_1min_and_3mins, 0) AS between_1min_and_3mins_perc,\r\n\t100.00 / (CASE WHEN o.total_calls IS NULL OR o.total_calls = 0 THEN 1 ELSE o.total_calls END) * coalesce(o.more_than_3mins, 0) AS more_than_3mins_perc,\r\n\t100.00 / (CASE WHEN o.total_calls IS NULL OR o.total_calls = 0 THEN 1 ELSE o.total_calls END) * coalesce(o.cost_less_than_1, 0) AS cost_less_than_1_perc,\r\n\t100.00 / (CASE WHEN o.total_calls IS NULL OR o.total_calls = 0 THEN 1 ELSE o.total_calls END) * coalesce(o.cost_between_1_and_2, 0) AS cost_between_1_and_2_perc,\r\n\t100.00 / (CASE WHEN o.total_calls IS NULL OR o.total_calls = 0 THEN 1 ELSE o.total_calls END) * coalesce(o.cost_more_than_2, 0) AS cost_more_than_2_perc\r\nFROM outbound_counts AS o\r\n;"
    }
   ]
  },
  {
   "title": "Ausgehend Anrufkosten",
   "type": "piechart",
   "description": "Verteilung der ausgehenden Anrufkosten",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Anrufverkehr (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf des Anrufverkehrs (ein- und ausgehend)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Angenommene Eingehende",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "-------------------------------\r\n-- Inbound answered connections\r\n-------------------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at,\r\n\t\tc.cdr_ended_at,\r\n\t\tDATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at) ELSE 0 END AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = 1\r\n\tAND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at,\r\n\t\tc.cdr_ended_at,\r\n\t\tDATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tcoalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM public_cdroutput AS c\r\n\t-- LEFT JOIN public_cdrbilling AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming = 1\r\n\tAND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT *\r\nFROM inbound_connections AS c\r\nORDER BY c.started_at DESC\r\n;"
    }
   ]
  },
  {
   "title": "Angenommene Ausgehende",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "--------------------------------\r\n-- Outbound answered connections\r\n--------------------------------\r\nWITH outbound_connections AS (\r\n  --------------\r\n  -- Destination\r\n  --------------\r\n  SELECT\r\n\t\tc.main_call_history_id,\r\n    --\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at,\r\n\t\tc.cdr_ended_at,\r\n\t\tDATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tcoalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0) AS talking_duration,\r\n\t\tround(coalesce(CAST(b.destination_bill_rate AS numeric(38, 2)), 0.00) * coalesce(DATEDIFF(MICROSECOND, 0, CAST(b.destination_bill_duration AS TIME)) / 60000000.00, 0.00), 2) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.destination_entity_type = 'external_line'\r\n  AND c.destination_participant_is_incoming = 0\r\n  AND c.cdr_answered_at IS NOT NULL\r\n  UNION ALL\r\n  ---------\r\n  -- Source\r\n  ---------\r\n  SELECT\r\n\t\tc.main_call_history_id,\r\n    --\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number + ' ' + coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n    --\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number + ' ' + coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at,\r\n\t\tc.cdr_ended_at,\r\n\t\tDATEDIFF(SECOND, c.cdr_started_at, c.cdr_ended_at) AS duration,\r\n\t\tcoalesce(DATEDIFF(SECOND, c.cdr_answered_at, c.cdr_ended_at), 0) AS talking_duration,\r\n\t\tround(coalesce(CAST(b.source_bill_rate AS numeric(38, 2)), 0.00) * coalesce(DATEDIFF(MICROSECOND, 0, CAST(b.source_bill_duration AS TIME)) / 60000000.00, 0.00), 2) AS bill_cost\r\n  FROM public_cdroutput AS c\r\n  LEFT JOIN public_cdrbilling AS b ON\r\n    b.cdr_id = c.cdr_id\r\n  WHERE $__timeFilter(c.cdr_started_at)\r\n  AND c.source_entity_type = 'external_line'\r\n  AND c.source_participant_is_incoming = 0\r\n  AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT *\r\nFROM outbound_connections AS c\r\nORDER BY c.started_at DESC\r\n;"
    }
   ]
  }
 ]
}