{
 "title": "13. Anrufqualitäts-Überwachung (MSSQL)",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Anrufqualitäts-Überwachung" } },
  {
   "title": "Ø Jitter",
   "type": "stat",
   "description": "Durchschnittlicher Jitter-Wert der Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN avg(q.a_rx_jitter) IS NULL AND avg(q.b_rx_jitter) IS NULL AND avg(q.a_tx_jitter) IS NULL AND avg(q.b_tx_jitter) IS NULL\r\n      THEN NULL\r\n    ELSE coalesce(avg(q.a_rx_jitter), 0) + coalesce(avg(q.b_rx_jitter), 0) + coalesce(avg(q.a_tx_jitter), 0) + coalesce(avg(q.b_tx_jitter), 0)\r\n  END\r\n  /\r\n  CASE\r\n    WHEN coalesce(avg(q.a_rx_jitter), 0) = 0 AND coalesce(avg(q.b_rx_jitter), 0) = 0 AND coalesce(avg(q.a_tx_jitter), 0) = 0 AND coalesce(avg(q.b_tx_jitter), 0) = 0 THEN 1\r\n    ELSE\r\n      CASE\r\n        WHEN avg(q.a_rx_jitter) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.b_rx_jitter) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.a_tx_jitter) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.b_tx_jitter) >= 0 THEN 1 ELSE 0\r\n      END\r\n  END\r\n  AS avg_jitter\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\n;"
    }
   ]
  },
  {
   "title": "Ø Paketverlust %",
   "type": "stat",
   "description": "Durchschnittlicher Paketverlust der Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN avg(q.a_rx_loss) IS NULL AND avg(q.b_rx_loss) IS NULL AND avg(q.a_tx_loss) IS NULL AND avg(q.b_tx_loss) IS NULL\r\n      THEN NULL\r\n    ELSE coalesce(avg(q.a_rx_loss), 0) + coalesce(avg(q.b_rx_loss), 0) + coalesce(avg(q.a_tx_loss), 0) + coalesce(avg(q.b_tx_loss), 0)\r\n  END\r\n  /\r\n  CASE\r\n    WHEN coalesce(avg(q.a_rx_loss), 0) = 0 AND coalesce(avg(q.b_rx_loss), 0) = 0 AND coalesce(avg(q.a_tx_loss), 0) = 0 AND coalesce(avg(q.b_tx_loss), 0) = 0 THEN 1\r\n    ELSE\r\n      CASE\r\n        WHEN avg(q.a_rx_loss) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.b_rx_loss) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.a_tx_loss) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.b_tx_loss) >= 0 THEN 1 ELSE 0\r\n      END\r\n  END\r\n  AS avg_loss\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\n;"
    }
   ]
  },
  {
   "title": "Ø Roundtrip-Zeit (ms)",
   "type": "stat",
   "description": "Durchschnittliche Roundtrip-Latenz der Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN avg(q.a_rtt) IS NULL AND avg(q.b_rtt) IS NULL\r\n      THEN NULL\r\n    ELSE coalesce(avg(q.a_rtt), 0) + coalesce(avg(q.b_rtt), 0)\r\n  END\r\n  /\r\n  CASE\r\n    WHEN coalesce(avg(q.a_rtt), 0) = 0 AND coalesce(avg(q.b_rtt), 0) = 0 THEN 1\r\n    ELSE\r\n      CASE\r\n        WHEN avg(q.a_rtt) >= 0 THEN 1 ELSE 0\r\n      END +\r\n      CASE\r\n        WHEN avg(q.b_rtt) >= 0 THEN 1 ELSE 0\r\n      END\r\n  END\r\n  AS avg_rtt\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\n;"
    }
   ]
  },
  {
   "title": "Qualitätswert (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf des MOS-Qualitätswerts",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 2 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  DATEADD(MINUTE, DATEDIFF(MINUTE, 0, q.time_stamp), 0) AS time_bucket,\r\n  -- MSSQL 2022 +\r\n  avg(LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx)) AS mos_score\r\n  -- < MSSQL 2022\r\n  -- AVG(\r\n  --     (\r\n  --       SELECT MIN(val)\r\n  --       FROM (VALUES \r\n  --           (q.a_mos_to_pbx), \r\n  --           (q.b_mos_to_pbx), \r\n  --           (q.a_mos_from_pbx), \r\n  --           (q.b_mos_from_pbx)\r\n  --       ) AS vals(val)\r\n  --     )\r\n  -- ) AS mos_score\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nGROUP BY DATEADD(MINUTE, DATEDIFF(MINUTE, 0, q.time_stamp), 0)\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Codec-Verteilung",
   "type": "barchart",
   "description": "Übersicht der verwendeten Audio-Codecs",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "WITH ab_stat AS (\r\n  SELECT\r\n    q.a_codec AS codec,\r\n    COUNT(*) AS row_count\r\n  FROM public_cl_quality AS q\r\n  WHERE $__timeFilter(q.time_stamp)\r\n  GROUP BY q.a_codec\r\n  UNION ALL\r\n  SELECT\r\n    q.b_codec AS codec,\r\n    COUNT(*) AS row_count\r\n  FROM public_cl_quality AS q\r\n  WHERE $__timeFilter(q.time_stamp)\r\n  GROUP BY q.b_codec\r\n)\r\nSELECT\r\n  s.codec,\r\n  sum(s.row_count) AS row_count\r\nFROM ab_stat AS s\r\nGROUP BY s.codec\r\nORDER BY row_count\r\n;"
    }
   ]
  },
  {
   "title": "Ø Paketverlust (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf des durchschnittlichen Paketverlusts",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  DATEADD(MINUTE, DATEDIFF(MINUTE, 0, q.time_stamp), 0) AS time_bucket,\r\n  avg(\r\n    CASE\r\n      WHEN q.a_rx_loss IS NULL AND q.b_rx_loss IS NULL AND q.a_tx_loss IS NULL AND q.b_tx_loss IS NULL\r\n        THEN 0\r\n      ELSE coalesce(q.a_rx_loss, 0) + coalesce(q.b_rx_loss, 0) + coalesce(q.a_tx_loss, 0) + coalesce(q.b_tx_loss, 0)\r\n    END\r\n    /\r\n    CASE\r\n      WHEN coalesce(q.a_rx_loss, 0) = 0 AND coalesce(q.b_rx_loss, 0) = 0 AND coalesce(q.a_tx_loss, 0) = 0 AND coalesce(q.b_tx_loss, 0) = 0 THEN 1\r\n      ELSE\r\n        CASE\r\n          WHEN q.a_rx_loss >= 0 THEN 1 ELSE 0\r\n        END +\r\n        CASE\r\n          WHEN q.b_rx_loss >= 0 THEN 1 ELSE 0\r\n        END +\r\n        CASE\r\n          WHEN q.a_tx_loss >= 0 THEN 1 ELSE 0\r\n        END +\r\n        CASE\r\n          WHEN q.b_tx_loss >= 0 THEN 1 ELSE 0\r\n        END\r\n    END\r\n  ) AS avg_loss\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nGROUP BY DATEADD(MINUTE, DATEDIFF(MINUTE, 0, q.time_stamp), 0)\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Gesamtwert-Verteilung",
   "type": "barchart",
   "description": "Verteilung der Anrufe nach MOS-Gesamtwert",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  0 AS row_order,\r\n  'Unknown' AS mos_overall_score,\r\n  count(*) AS number_of_calls\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nAND (LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) IS NULL OR LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 0.1)\r\nUNION ALL\r\nSELECT\r\n  1 AS row_order,\r\n  'Poor' AS mos_overall_score,\r\n  count(*) AS number_of_calls\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nAND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) >= 0.1 AND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 3.1\r\nUNION ALL\r\nSELECT\r\n  2 AS row_order,\r\n  'Low' AS mos_overall_score,\r\n  count(*) AS number_of_calls\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nAND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) >= 3.1 AND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 3.5\r\nUNION ALL\r\nSELECT\r\n  3 AS row_order,\r\n  'Medium' AS mos_overall_score,\r\n  count(*) AS number_of_calls\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nAND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) >= 3.5 AND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 3.8\r\nUNION ALL\r\nSELECT\r\n  4 AS row_order,\r\n  'High' AS mos_overall_score,\r\n  count(*) AS number_of_calls\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nAND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) >= 3.8 AND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 4.2\r\nUNION ALL\r\nSELECT\r\n  5 AS row_order,\r\n  'Excellent' AS mos_overall_score,\r\n  count(*) AS number_of_calls\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nAND LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) >= 4.2\r\nORDER BY row_order\r\n;"
    }
   ]
  },
  {
   "title": "Anrufqualitätsbericht",
   "type": "table",
   "description": "Detaillierter Qualitätsbericht aller Anrufe mit Jitter, Paketverlust und Latenz",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "cdr_db",
     "rawSql": "SELECT\r\n  q.time_stamp AS started_at,\r\n  CASE\r\n    WHEN q.summary = 0  -- 0 = Unknown\r\n      -- CQSummaryUnknown = Incomplete\r\n      THEN N'⚠️ ' + 'Incomplete'\r\n    WHEN q.summary = 1  -- 1 = AllGood\r\n      -- CQSummaryAllGood = No problems detected\r\n      THEN N'✅ ' + 'No problems detected'\r\n    WHEN q.summary = 2  -- 2 = NetworkToParty1 [NetworkToP1]\r\n      -- CQSummaryToP1 = Network problems from PBX to %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems from PBX to %s', coalesce(q.a_number, 'Unknown'))\r\n    WHEN q.summary = 3  -- 3 = NetworkFromParty1 [NetworkFromP1]\r\n      -- CQSummaryFromP1 = Network problems from %s to PBX\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems from %s to PBX', coalesce(q.a_number, 'Unknown'))\r\n    WHEN q.summary = 4  -- 4 = NetworkParty1AndPbx [NetworkP1andPbx]\r\n      -- CQSummaryP1andPbx = Network problems between PBX and %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems between PBX and %s', coalesce(q.a_number, 'Unknown'))\r\n    WHEN q.summary = 5  -- 5 = NetworkToParty2 [NetworkToP2]\r\n      -- CQSummaryToP1 = Network problems from PBX to %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems from PBX to %s', coalesce(q.b_number, 'Unknown'))\r\n    WHEN q.summary = 6  -- 6 = NetworkFromParty2 [NetworkFromP2]\r\n      -- CQSummaryFromP1 = Network problems from %s to PBX\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems from %s to PBX', coalesce(q.b_number, 'Unknown'))\r\n    WHEN q.summary = 7  -- 7 = NetworkParty2AndPbx [NetworkP2andPbx]\r\n      -- CQSummaryP1andPbx = Network problems between PBX and %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems between PBX and %s', coalesce(q.b_number, 'Unknown'))\r\n    WHEN q.summary = 8  -- 8 = ToPbx\r\n      -- CQSummaryToPbx = Network problems in direction to PBX from both %s and %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems in direction to PBX from both %s and %s', coalesce(q.a_number, 'Unknown'), coalesce(q.b_number, 'Unknown'))\r\n    WHEN q.summary = 9  -- 9 = FromPbx\r\n      -- CQSummaryFromPbx = Network problems in direction from PBX to both %s and %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems in direction from PBX to both %s and %s', coalesce(q.a_number, 'Unknown'), coalesce(q.b_number, 'Unknown'))\r\n    WHEN q.summary = 10  -- 10 = FromToPbX\r\n      -- CQSummaryFromToPbX = Network problems between PBX and both %s and %s\r\n      THEN N'⚠️ ' + FORMATMESSAGE('Network problems between PBX and both %s and %s', coalesce(q.a_number, 'Unknown'), coalesce(q.b_number, 'Unknown'))\r\n    ELSE N'⚠️ ' + 'Generic Problems'\r\n  END AS summary_overal,\r\n  CASE\r\n    WHEN q.summary = 0  -- 0 = Unknown\r\n      THEN 'Direct (RTP stream bypass)'\r\n    WHEN q.transcoding = 1\r\n      THEN 'Transcoding'\r\n    ELSE 'Proxy'\r\n  END AS mode,\r\n  CASE\r\n    WHEN LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) IS NULL OR LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 0.1\r\n      THEN 'Unknown'\r\n    WHEN LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 3.1\r\n      THEN 'Poor'\r\n    WHEN LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 3.5\r\n      THEN 'Low'\r\n    WHEN LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 3.8\r\n      THEN 'Medium'\r\n    WHEN LEAST(q.a_mos_to_pbx, q.b_mos_to_pbx, q.a_mos_from_pbx, q.b_mos_from_pbx) < 4.2\r\n      THEN 'High'\r\n    ELSE 'Excellent'\r\n  END AS mos_overall_score,\r\n  CASE\r\n    WHEN q.a_mos_to_pbx IS NULL OR q.a_mos_to_pbx < 0.1\r\n      THEN 'Unknown'\r\n    WHEN q.a_mos_to_pbx < 3.1\r\n      THEN 'Poor'\r\n    WHEN q.a_mos_to_pbx < 3.5\r\n      THEN 'Low'\r\n    WHEN q.a_mos_to_pbx < 3.8\r\n      THEN 'Medium'\r\n    WHEN q.a_mos_to_pbx < 4.2\r\n      THEN 'High'\r\n    ELSE 'Excellent'\r\n  END AS a_mos_to_pbx_score,\r\n  CASE\r\n    WHEN q.b_mos_to_pbx IS NULL OR q.b_mos_to_pbx < 0.1\r\n      THEN 'Unknown'\r\n    WHEN q.b_mos_to_pbx < 3.1\r\n      THEN 'Poor'\r\n    WHEN q.b_mos_to_pbx < 3.5\r\n      THEN 'Low'\r\n    WHEN q.b_mos_to_pbx < 3.8\r\n      THEN 'Medium'\r\n    WHEN q.b_mos_to_pbx < 4.2\r\n      THEN 'High'\r\n    ELSE 'Excellent'\r\n  END AS b_mos_to_pbx_score,\r\n  CASE\r\n    WHEN q.a_mos_from_pbx IS NULL OR q.a_mos_from_pbx < 0.1\r\n      THEN 'Unknown'\r\n    WHEN q.a_mos_from_pbx < 3.1\r\n      THEN 'Poor'\r\n    WHEN q.a_mos_from_pbx < 3.5\r\n      THEN 'Low'\r\n    WHEN q.a_mos_from_pbx < 3.8\r\n      THEN 'Medium'\r\n    WHEN q.a_mos_from_pbx < 4.2\r\n      THEN 'High'\r\n    ELSE 'Excellent'\r\n  END AS a_mos_from_pbx_score,\r\n  CASE\r\n    WHEN q.b_mos_from_pbx IS NULL OR q.b_mos_from_pbx < 0.1\r\n      THEN 'Unknown'\r\n    WHEN q.b_mos_from_pbx < 3.1\r\n      THEN 'Poor'\r\n    WHEN q.b_mos_from_pbx < 3.5\r\n      THEN 'Low'\r\n    WHEN q.b_mos_from_pbx < 3.8\r\n      THEN 'Medium'\r\n    WHEN q.b_mos_from_pbx < 4.2\r\n      THEN 'High'\r\n    ELSE 'Excellent'\r\n  END AS b_mos_from_pbx_score,\r\n  q.a_number + ' ' + coalesce(q.a_name, 'Unknown') AS a_participant,\r\n  q.a_duration,   -- in seconds\r\n  q.b_number + ' ' + coalesce(q.b_name, 'Unknown') AS b_participant,\r\n  q.b_duration,   -- in seconds\r\n  CASE\r\n    WHEN q.a_location IS NULL THEN ''\r\n    WHEN q.a_location = 0 THEN 'Local'\r\n    WHEN q.a_location = 1 THEN 'External'\r\n    WHEN q.a_location = 2 THEN 'Tunnel'\r\n    WHEN q.a_location = 3 THEN 'STUN'\r\n  END AS a_location_type,\r\n  CASE\r\n    WHEN q.b_location IS NULL THEN ''\r\n    WHEN q.b_location = 0 THEN 'Local'\r\n    WHEN q.b_location = 1 THEN 'External'\r\n    WHEN q.b_location = 2 THEN 'Tunnel'\r\n    WHEN q.b_location = 3 THEN 'STUN'\r\n  END AS b_location_type,\r\n  coalesce(q.a_tun_address, 'Unknown') AS a_address,\r\n  coalesce(q.b_tun_address, 'Unknown') AS b_address,\r\n  q.a_codec,\r\n  q.b_codec,\r\n  q.a_rtt,\r\n  q.b_rtt,\r\n  q.a_rx,\r\n  q.a_rx_loss,\r\n  q.a_rx_jitter,\r\n  q.b_rx,\r\n  q.b_rx_loss,\r\n  q.b_rx_jitter,\r\n  q.a_tx,\r\n  q.a_tx_loss,\r\n  q.a_tx_jitter,\r\n  q.b_tx,\r\n  q.b_tx_loss,\r\n  q.b_tx_jitter\r\nFROM public_cl_quality AS q\r\nWHERE $__timeFilter(q.time_stamp)\r\nORDER BY q.time_stamp DESC\r\n;"
    }
   ]
  }
 ]
}