{
 "title": "02. Rufgruppen (BigQuery)",
 "description": "Ring group dashboard analytics",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "ring_group",
    "label": "Ring group",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ${ring_group:text}" } },
  {
   "title": "Eingegangene Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der eingegangenen Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT rg.cdr_id) AS total_calls\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN rg.cdr_id\r\n    END\r\n  ) AS answered_calls\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN rg.cdr_id\r\n    END\r\n  ) * 100.0 /\r\n  COUNT(DISTINCT rg.cdr_id)\r\n  AS percent_answered\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nHAVING COUNT(DISTINCT rg.cdr_id) > 0\r\n;"
    }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  COALESCE(COUNT(DISTINCT rg.cdr_id), 0) -\r\n  COALESCE(COUNT(DISTINCT\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN rg.cdr_id\r\n    END\r\n  ), 0)\r\n  AS unanswered_calls\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  SUM(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, continued_in_cdr.cdr_answered_at, SECOND)\r\n    END\r\n  ) AS total_talking_time\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  AVG(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, continued_in_cdr.cdr_answered_at, SECOND)\r\n    END\r\n  ) AS total_talking_time\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  AVG(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, rg.cdr_started_at, SECOND)\r\n      ELSE TIMESTAMP_DIFF(rg.cdr_ended_at, rg.cdr_started_at, SECOND)\r\n    END\r\n  ) AS duration\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "Längste Anrufdauer",
   "type": "stat",
   "description": "Dauer des längsten Anrufs im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  MAX(\r\n    CASE\r\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, rg.cdr_started_at, SECOND)\r\n      ELSE TIMESTAMP_DIFF(rg.cdr_ended_at, rg.cdr_started_at, SECOND)\r\n    END\r\n  ) AS duration\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\n;"
    }
   ]
  },
  {
   "title": "% Verpasste Anrufe",
   "type": "gauge",
   "description": "Prozentualer Anteil nicht angenommener Anrufe",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT\r\n    CASE\r\n      WHEN NOT (rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension')\r\n      THEN rg.cdr_id\r\n    END\r\n  ) * 100.0 /\r\n  COUNT(DISTINCT rg.cdr_id)\r\n  AS missed_call_rate\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nHAVING COUNT(DISTINCT rg.cdr_id) > 0\r\n;"
    }
   ]
  },
  {
   "title": "Ø Klingelzeit",
   "type": "stat",
   "description": "Durchschnittliche Wartezeit bis zur Annahme",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n  AVG(TIMESTAMP_DIFF(rg.cdr_ended_at, rg.cdr_started_at, SECOND)) AS duration\nFROM `3cx_call_data.public_cdroutput` AS rg\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n;"
    }
   ]
  },
  {
   "title": "Anrufergebnis",
   "type": "piechart",
   "description": "Verteilung der Anrufergebnisse (angenommen, verpasst, etc.)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n    CASE\n      WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN COALESCE(continued_in_cdr.termination_reason, 'other')\n      ELSE COALESCE('not_answered__' || rg.termination_reason, 'other')\n    END\n    AS call_outcome,\n    COUNT(*) AS call_count\nFROM `3cx_call_data.public_cdroutput` AS rg\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY call_outcome\nORDER BY call_count DESC\n;"
    }
   ]
  },
  {
   "title": "Eingegangene / Angenommene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Zeitlicher Vergleich von eingegangenen und angenommenen Anrufen",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n    TIMESTAMP_TRUNC(rg.cdr_started_at, HOUR) AS call_time,\n    COUNT(DISTINCT rg.cdr_id) AS total_calls,\n    COUNT(DISTINCT\n    CASE\n        WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN rg.cdr_id\n    END\n    ) AS answered_calls\nFROM `3cx_call_data.public_cdroutput` AS rg\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = rg.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY call_time\nORDER BY call_time\n;"
    }
   ]
  },
  {
   "title": "Rufgruppen-Statistik",
   "type": "table",
   "description": "Ring group call statistics",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "-- Ring group info with last name\nWITH rg_info AS (\n\tSELECT\n\t\trg.destination_dn_number AS dn_number,\n\t\tCASE WHEN '${ring_group:value}' = 'All' THEN 'All ring groups' ELSE COALESCE(rg.destination_dn_name, 'Unknown') END AS name\n\tFROM `3cx_call_data.public_cdroutput` AS rg\n\tWHERE rg.cdr_id = (\n\t\tSELECT\n\t\t\tMAX(rg.cdr_id)\n\t\tFROM `3cx_call_data.public_cdroutput` AS rg\n\t\tWHERE $__timeFilter(rg.cdr_started_at)\n      AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n  \t  AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n\t)\n),\n-- Ring group totals\nrg_totals AS (\n\tSELECT\n    0 AS row_order_no,\n\t\tMAX(rg.destination_dn_number) AS rg_dn,\n\t\tMAX(rg_info.name) AS rg_name,\n\t\tCOUNT(DISTINCT rg.cdr_id) AS rg_received_count,\n\t\tCOUNT(DISTINCT\n\t\t\tCASE\n\t\t\t\tWHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n\t\t\t\tTHEN rg.cdr_id\n\t\t\tEND\n\t\t) AS rg_answered_count\n\tFROM `3cx_call_data.public_cdroutput` AS rg\n\tINNER JOIN rg_info ON TRUE\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\n\t\tcontinued_in_cdr.cdr_id = rg.continued_in_cdr_id\n\t\tAND continued_in_cdr.creation_forward_reason = 'polling'\n\tWHERE $__timeFilter(rg.cdr_started_at)\n    AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n\t  AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n\t--GROUP BY rg_dn\n),\n-- Ring group users statistics\nrg_users_stat AS (\n  SELECT\n    1 AS row_order_no,\n    MAX(rg.destination_dn_number) AS rg_dn,\n    MAX(rg_info.name) AS rg_name,\n    agent_polls.destination_dn_number AS agent_dn,\n    COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent_name,\n    COUNT(DISTINCT CASE WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN rg.cdr_id END) AS agent_answered_polls_count,\n    COUNT(agent_polls.cdr_id) AS agent_received_polls_count\n  FROM `3cx_call_data.public_cdroutput` AS rg\n  INNER JOIN rg_info ON TRUE\n  INNER JOIN `3cx_call_data.public_cdroutput` AS agent_polls ON\n    agent_polls.call_history_id = rg.call_history_id\n    AND agent_polls.originating_cdr_id = rg.cdr_id\n    AND agent_polls.destination_dn_type = 'extension'\n    AND agent_polls.creation_method = 'route_to'\n    AND agent_polls.creation_forward_reason = 'polling'\n  WHERE $__timeFilter(rg.cdr_started_at)\n    AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n    AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\n  GROUP BY agent_polls.destination_dn_number, agent_polls.destination_dn_name\n  --ORDER BY agent_dn, agent_polls.destination_dn_name\n)\nSELECT\n  rg.row_order_no,\n  CASE WHEN '${ring_group:value}' != 'All' THEN rg.rg_dn || ' ' ELSE '' END || rg.rg_name || ' [totals]' AS extension,\n  COALESCE(rg.rg_received_count, 0) AS calls_received,\n  COALESCE(rg.rg_received_count, 0) - COALESCE(rg.rg_answered_count, 0) AS calls_unanswered,\n  COALESCE(rg.rg_answered_count, 0) AS calls_answered,\n  CAST(NULL AS bigint) AS polls_received,\n  CAST(NULL AS bigint) AS polls_missed\nFROM rg_totals AS rg\nUNION ALL\nSELECT\n  u.row_order_no,\n  u.agent_dn || ' ' || u.agent_name AS extension,\n  CAST(NULL AS bigint) AS calls_received,\n  CAST(NULL AS bigint) AS calls_unanswered,\n  COALESCE(u.agent_answered_polls_count, 0) AS calls_answered,\n  COALESCE(u.agent_received_polls_count, 0) AS polls_received,\n  COALESCE(u.agent_received_polls_count, 0) - COALESCE(u.agent_answered_polls_count) AS polls_missed\nFROM rg_users_stat AS u\nORDER BY row_order_no, extension\n;"
    }
   ]
  },
  {
   "title": "Eingegangene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Time series Graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n    TIMESTAMP_TRUNC(rg.cdr_started_at, HOUR) AS time_bucket,\r\n    COUNT(DISTINCT rg.cdr_id) AS num_calls\r\nFROM `3cx_call_data.public_cdroutput` AS rg\r\nWHERE $__timeFilter(rg.cdr_started_at)\r\nAND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\r\nAND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\r\nGROUP BY time_bucket\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Anrufstatistik nach Rufgruppenmitgliedern",
   "type": "barchart",
   "description": "This shows the number of answered calls per extension in the ring group.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n  agent_polls.destination_dn_number || ' ' || COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent,\n  COUNT(DISTINCT agent_polls.main_call_history_id) AS agent_received_calls_count,\n  COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\n  COUNT(DISTINCT CASE WHEN rg.termination_reason IN ('continued_in', 'redirected') AND rg.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN rg.cdr_id END) AS agent_answered_polls_count\nFROM `3cx_call_data.public_cdroutput` AS rg\nINNER JOIN `3cx_call_data.public_cdroutput` AS agent_polls ON\n  agent_polls.call_history_id = rg.call_history_id\n  AND agent_polls.originating_cdr_id = rg.cdr_id\n  AND agent_polls.destination_dn_type = 'extension'\n  AND agent_polls.creation_method = 'route_to'\n  AND agent_polls.creation_forward_reason = 'polling'\nWHERE $__timeFilter(rg.cdr_started_at)\n  AND ('${ring_group:value}' = 'All' OR rg.destination_dn_number = '${ring_group:value}')\n  AND rg.destination_dn_type IN ('ring_group_ring_all', 'ring_group_hunt')\nGROUP BY agent\nORDER BY agent\n;"
    }
   ]
  }
 ]
}