{
 "title": "03. Warteschlangen (BigQuery)",
 "description": "Queues Dashboard and Analytics",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# ${queue:text}" } },
  {
   "title": "Eingegangene Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der eingegangenen Anrufe im Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  SUM(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, continued_in_cdr.cdr_answered_at, SECOND)\r\n    END\r\n  ) AS total_talking_time\r\nFROM `3cx_call_data.public_cdroutput` AS q\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Längste Anrufdauer",
   "type": "stat",
   "description": "Dauer des längsten Anrufs im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  MAX(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, q.cdr_started_at, SECOND)\r\n      ELSE TIMESTAMP_DIFF(q.cdr_ended_at, q.cdr_started_at, SECOND)\r\n    END\r\n  ) AS duration\r\nFROM `3cx_call_data.public_cdroutput` AS q\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Ø Klingelzeit",
   "type": "stat",
   "description": "Durchschnittliche Wartezeit bis zur Annahme",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n  AVG(TIMESTAMP_DIFF(q.cdr_ended_at, q.cdr_started_at, SECOND)) AS duration\nFROM `3cx_call_data.public_cdroutput` AS q\nWHERE $__timeFilter(q.cdr_started_at)\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\nAND q.destination_dn_type = 'queue'\n;"
    }
   ]
  },
  {
   "title": "Anrufergebnis",
   "type": "piechart",
   "description": "Verteilung der Anrufergebnisse (angenommen, verpasst, etc.)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n    CASE\n        WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN COALESCE(continued_in_cdr.termination_reason, 'other')\n        ELSE COALESCE('not_answered__' || q.termination_reason, 'other')\n    END\n    AS call_outcome,\n    COUNT(*) AS call_count\nFROM `3cx_call_data.public_cdroutput` AS q\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(q.cdr_started_at)\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\nAND q.destination_dn_type = 'queue'\nGROUP BY call_outcome\nORDER BY call_count DESC\n;"
    }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "% Calls Not Answered",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Rückrufe bearbeitet [auto]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  AVG(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n      THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, continued_in_cdr.cdr_answered_at, SECOND)\r\n    END\r\n  ) AS total_talking_time\r\nFROM `3cx_call_data.public_cdroutput` AS q\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n  AVG(\r\n    CASE\r\n      WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\r\n        THEN TIMESTAMP_DIFF(continued_in_cdr.cdr_ended_at, q.cdr_started_at, SECOND)\r\n      ELSE TIMESTAMP_DIFF(q.cdr_ended_at, q.cdr_started_at, SECOND)\r\n    END\r\n  ) AS duration\r\nFROM `3cx_call_data.public_cdroutput` AS q\r\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\r\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\r\n  AND continued_in_cdr.creation_forward_reason = 'polling'\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\n;"
    }
   ]
  },
  {
   "title": "Eingegangene / Angenommene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Zeitlicher Vergleich von eingegangenen und angenommenen Anrufen",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n    TIMESTAMP_TRUNC(q.cdr_started_at, HOUR) AS call_time,\n    COUNT(DISTINCT q.cdr_id) AS total_calls,\n    COUNT(DISTINCT\n    CASE\n        WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n        THEN q.cdr_id\n    END\n    ) AS answered_calls\nFROM `3cx_call_data.public_cdroutput` AS q\nLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\n  continued_in_cdr.cdr_id = q.continued_in_cdr_id\n  AND continued_in_cdr.creation_forward_reason = 'polling'\nWHERE $__timeFilter(q.cdr_started_at)\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\nAND q.destination_dn_type = 'queue'\nGROUP BY call_time\nORDER BY call_time\n;"
    }
   ]
  },
  {
   "title": "Warteschlangen-Statistik",
   "type": "table",
   "description": "Detaillierte Anrufstatistik der Warteschlange im Zeitraum",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "-- Queue info with last name\nWITH q_info AS (\n\tSELECT\n\t\tq.destination_dn_number AS dn_number,\n    CASE WHEN '${queue:value}' = 'All' THEN 'All queues' ELSE COALESCE(q.destination_dn_name, 'Unknown') END AS name\n\tFROM `3cx_call_data.public_cdroutput` AS q\n\tWHERE q.cdr_id = (\n\t\tSELECT\n\t\t\tMAX(q.cdr_id)\n\t\tFROM `3cx_call_data.public_cdroutput` AS q\n\t\tWHERE $__timeFilter(q.cdr_started_at)\n  \t  AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\n      AND q.destination_dn_type = 'queue'\n\t)\n),\n-- Queue totals\nq_totals AS (\n\tSELECT\n    0 AS row_order_no,\n\t\tMAX(q.destination_dn_number) AS q_dn,\n\t\tMAX(q_info.name) AS q_name,\n\t\tCOUNT(DISTINCT q.cdr_id) AS q_received_count,\n\t\tCOUNT(DISTINCT\n\t\t\tCASE\n\t\t\t\tWHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND continued_in_cdr.cdr_id IS NOT NULL AND continued_in_cdr.cdr_answered_at IS NOT NULL AND continued_in_cdr.destination_entity_type = 'extension'\n\t\t\t\tTHEN q.cdr_id\n\t\t\tEND\n\t\t) AS q_answered_count,\n    COUNT(DISTINCT cbi.cdr_id) AS qcb_serviced_count\n\tFROM `3cx_call_data.public_cdroutput` AS q\n\tINNER JOIN q_info ON TRUE\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS continued_in_cdr ON\n\t\tcontinued_in_cdr.cdr_id = q.continued_in_cdr_id\n\t\tAND continued_in_cdr.creation_forward_reason = 'polling'\n  LEFT JOIN `3cx_call_data.public_cdroutput` AS qcb ON\n    q.termination_reason = 'continued_in'\n    AND q.termination_reason_details = 'callback_requested'\n    AND qcb.cdr_id = q.continued_in_cdr_id\n    AND qcb.creation_forward_reason = 'callback_requested'\n    AND qcb.source_entity_type = 'queue'\n    AND qcb.destination_dn_number = 'QCB'\n    AND qcb.termination_reason = 'continued_in'\n  LEFT JOIN `3cx_call_data.public_cdroutput` AS cb ON\n    cb.cdr_id = qcb.continued_in_cdr_id\n    AND cb.source_dn_number = 'QCB'\n    AND cb.continued_in_cdr_id IS NOT NULL\n    AND cb.termination_reason_details = 'callback'\n  LEFT JOIN `3cx_call_data.public_cdroutput` AS cbi ON\n    cbi.cdr_id = cb.continued_in_cdr_id\n    AND cbi.creation_method = 'route_to'\n    AND cbi.cdr_answered_at IS NOT NULL\n\tWHERE $__timeFilter(q.cdr_started_at)\n    AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\n    AND q.destination_dn_type = 'queue'\n),\nqcb_user_stat AS (\n  SELECT\n    MAX(q.destination_dn_number) AS q_dn,\n    MAX(q_info.name) AS q_name,\n    cbi.source_dn_number AS agent_dn,\n    COALESCE(cbi.source_dn_name, 'Unknown') AS agent_name,\n    0 AS agent_answered_polls_count,\n    0 AS agent_received_polls_count,\n    COUNT(DISTINCT cbi.cdr_id) AS agent_qcb_serviced_count\n  FROM `3cx_call_data.public_cdroutput` AS q\n  INNER JOIN q_info ON TRUE\n  INNER JOIN `3cx_call_data.public_cdroutput` AS qcb ON\n    q.termination_reason = 'continued_in'\n    AND q.termination_reason_details = 'callback_requested'\n    AND qcb.cdr_id = q.continued_in_cdr_id\n    AND qcb.creation_forward_reason = 'callback_requested'\n    AND qcb.source_entity_type = 'queue'\n    AND qcb.destination_dn_number = 'QCB'\n    AND qcb.termination_reason = 'continued_in'\n  INNER JOIN `3cx_call_data.public_cdroutput` AS cb ON\n    cb.cdr_id = qcb.continued_in_cdr_id\n    AND cb.source_dn_number = 'QCB'\n    AND cb.continued_in_cdr_id IS NOT NULL\n    AND cb.termination_reason_details = 'callback'\n  INNER JOIN `3cx_call_data.public_cdroutput` AS cbi ON\n    cbi.cdr_id = cb.continued_in_cdr_id\n    AND cbi.creation_method = 'route_to'\n    AND cbi.cdr_answered_at IS NOT NULL\n    AND cbi.source_dn_type = 'extension'\n  WHERE $__timeFilter(q.cdr_started_at)\n    AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\n    AND q.destination_entity_type = 'queue'\n    AND q.termination_reason = 'continued_in'\n    AND q.termination_reason_details = 'callback_requested'\n  GROUP BY cbi.source_dn_number, cbi.source_dn_name\n),\n-- Queue agents statistics\nq_user_stat AS (\n  SELECT\n    MAX(q.destination_dn_number) AS q_dn,\n    MAX(q_info.name) AS q_name,\n    agent_polls.destination_dn_number AS agent_dn,\n    COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent_name,\n    COUNT(DISTINCT CASE WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN q.cdr_id END) AS agent_answered_polls_count,\n    COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\n    0 AS agent_qcb_serviced_count\n  FROM `3cx_call_data.public_cdroutput` AS q\n  INNER JOIN q_info ON TRUE\n  INNER JOIN `3cx_call_data.public_cdroutput` AS agent_polls ON\n    agent_polls.call_history_id = q.call_history_id\n    AND agent_polls.originating_cdr_id = q.cdr_id\n    AND agent_polls.destination_dn_type = 'extension'\n    AND agent_polls.creation_method = 'route_to'\n    AND agent_polls.creation_forward_reason = 'polling'\n  WHERE $__timeFilter(q.cdr_started_at)\n    AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\n    AND q.destination_dn_type = 'queue'\n  GROUP BY agent_polls.destination_dn_number, agent_polls.destination_dn_name\n)\nSELECT\n  q.row_order_no,\n  CASE WHEN '${queue:value}' != 'All' THEN q.q_dn || ' ' ELSE '' END || q.q_name || ' [totals]' AS extension,\n  COALESCE(q.q_received_count, 0) AS calls_received,\n  COALESCE(q.q_received_count, 0) - COALESCE(q.q_answered_count, 0) - COALESCE(q.qcb_serviced_count, 0) AS calls_unanswered,\n  COALESCE(q.q_answered_count, 0) + COALESCE(q.qcb_serviced_count, 0) AS calls_answered,\n  COALESCE(q.qcb_serviced_count, 0) AS qcb_serviced,\n  CAST(NULL AS bigint) AS polls_received,\n  CAST(NULL AS bigint) AS polls_missed\nFROM q_totals AS q\nUNION ALL\nSELECT\n  u.row_order_no,\n  u.agent_dn || ' ' || u.agent_name AS extension,\n  CAST(NULL AS bigint) AS calls_received,\n  CAST(NULL AS bigint) AS calls_unanswered,\n  COALESCE(u.agent_answered_polls_count, 0) + COALESCE(u.agent_qcb_serviced_count, 0) AS calls_answered,\n  COALESCE(u.agent_qcb_serviced_count, 0) AS qcb_serviced,\n  COALESCE(u.agent_received_polls_count, 0) AS polls_received,\n  COALESCE(u.agent_received_polls_count, 0) - COALESCE(u.agent_answered_polls_count, 0) AS polls_missed\nFROM (\n  SELECT\n    1 AS row_order_no,\n    MAX(u.q_dn) AS q_dn,\n    MAX(u.q_name) AS q_name,\n    u.agent_dn AS agent_dn,\n    u.agent_name AS agent_name,\n    SUM(u.agent_answered_polls_count) AS agent_answered_polls_count,\n    SUM(u.agent_received_polls_count) AS agent_received_polls_count,\n    SUM(u.agent_qcb_serviced_count) AS agent_qcb_serviced_count\n  FROM (\n    SELECT *\n    FROM q_user_stat AS u\n    UNION ALL\n    SELECT *\n    FROM qcb_user_stat AS cb\n  ) AS u\n  GROUP BY u.agent_dn, u.agent_name\n) AS u\nORDER BY row_order_no, extension\n;"
    }
   ]
  },
  {
   "title": "Eingegangene Anrufe (Verlauf)",
   "type": "barchart",
   "description": "Time series Graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "project": "grafana3cx",
     "rawSql": "SELECT\r\n    TIMESTAMP_TRUNC(q.cdr_started_at, HOUR) AS time_bucket,\r\n    COUNT(DISTINCT q.cdr_id) AS num_calls\r\nFROM `3cx_call_data.public_cdroutput` AS q\r\nWHERE $__timeFilter(q.cdr_started_at)\r\nAND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\r\nAND q.destination_dn_type = 'queue'\r\nGROUP BY time_bucket\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Anrufstatistik nach Agenten",
   "type": "barchart",
   "description": "This shows the number of answered calls per extension in the queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "SELECT\n  agent_polls.destination_dn_number || ' ' || COALESCE(agent_polls.destination_dn_name, 'Unknown') AS agent,\n  COUNT(DISTINCT agent_polls.main_call_history_id) AS agent_received_calls_count,\n  COUNT(agent_polls.cdr_id) AS agent_received_polls_count,\n  COUNT(DISTINCT CASE WHEN q.termination_reason IN ('continued_in', 'redirected') AND q.termination_reason_details = 'polling' AND agent_polls.cdr_answered_at IS NOT NULL THEN q.cdr_id END) AS agent_answered_polls_count\nFROM `3cx_call_data.public_cdroutput` AS q\nINNER JOIN `3cx_call_data.public_cdroutput` AS agent_polls ON\n  agent_polls.call_history_id = q.call_history_id\n  AND agent_polls.originating_cdr_id = q.cdr_id\n  AND agent_polls.destination_dn_type = 'extension'\n  AND agent_polls.creation_method = 'route_to'\n  AND agent_polls.creation_forward_reason = 'polling'\nWHERE $__timeFilter(q.cdr_started_at)\n  AND ('${queue:value}' = 'All' OR q.destination_dn_number = '${queue:value}')\n  AND q.destination_dn_type = 'queue'\nGROUP BY agent\nORDER BY agent\n;"
    }
   ]
  }
 ]
}