{
 "title": "07. Ausgehende Anrufe (BigQuery)",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Ausgehende Anrufe" } },
  {
   "title": "Getätigte Anrufe",
   "type": "stat",
   "description": "Gesamtzahl der getätigten ausgehenden Anrufe",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "-----------------------\r\n-- Outbound connections\r\n-----------------------\r\nWITH outbound_connections AS (\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_started_at, SECOND) AS duration,\r\n\t\tTIMESTAMP_DIFF(coalesce(c.cdr_answered_at, c.cdr_ended_at), c.cdr_started_at, SECOND) AS ringing_duration,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND) ELSE 0 END AS talking_duration\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND \r\n\t(\r\n\t\t(c.destination_entity_type = 'outbound_rule' AND c.destination_participant_is_incoming = FALSE AND c.termination_reason NOT IN ('cancelled', 'continued_in', 'rejected', 'src_participant_terminated', 'dst_participant_terminated'))\r\n\t\tOR\r\n\t\t(c.destination_entity_type = 'external_line' AND c.destination_participant_is_incoming = FALSE)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Source\r\n\t--------------\r\n\tSELECT\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_started_at, SECOND) AS duration,\r\n\t\tTIMESTAMP_DIFF(coalesce(c.cdr_answered_at, c.cdr_ended_at), c.cdr_started_at, SECOND) AS ringing_duration,\r\n\t\tcoalesce(TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND), 0) AS talking_duration\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS b ON\r\n\t\tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = FALSE\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tCOUNT(DISTINCT c.participant_id) AS calls_received,\r\n\tCOUNT(DISTINCT CASE WHEN c.talking_duration > 0 THEN c.participant_id END) AS calls_answered,\r\n\tCOUNT(DISTINCT CASE WHEN c.talking_duration > 0 THEN c.participant_id END) * 100.0 / \r\n\t\tCASE WHEN COUNT(DISTINCT c.participant_id) = 0 THEN 1 ELSE COUNT(DISTINCT c.participant_id) END AS calls_answered_percent,\r\n\tCOUNT(DISTINCT c.participant_id) - COUNT(DISTINCT CASE WHEN c.talking_duration > 0 THEN c.participant_id END) AS calls_unanswered,\r\n\tSUM(c.talking_duration) AS talking_duration,\r\n\tSUM(c.talking_duration) / CASE WHEN COUNT(DISTINCT c.participant_id) = 0 THEN 1 ELSE COUNT(DISTINCT c.participant_id) END AS avg_talking_duration,\r\n\tSUM(c.duration) / CASE WHEN COUNT(DISTINCT c.participant_id) = 0 THEN 1 ELSE COUNT(DISTINCT c.participant_id) END AS avg_duration,\r\n\tSUM(c.duration) AS duration\r\nFROM outbound_connections AS c"
    }
   ]
  },
  {
   "title": "Angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "% Angenommene Anrufe",
   "type": "stat",
   "description": "Prozentualer Anteil der Anrufe, die erfolgreich angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Nicht angenommene Anrufe",
   "type": "stat",
   "description": "Anzahl der Anrufe, die nicht angenommen wurden",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Ø Gesprächsdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesprächszeit pro angenommenem Anruf",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Gesamte Gesprächsdauer",
   "type": "stat",
   "description": "Summe aller Gesprächszeiten im gewählten Zeitraum",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Ø Anrufdauer",
   "type": "stat",
   "description": "Durchschnittliche Gesamtdauer aller Anrufe inkl. Klingelzeit",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Total Call Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Ausgehende Anrufe (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf der ausgehenden Anrufe",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "-----------------------\r\n-- Outbound connections\r\n-----------------------\r\nWITH outbound_connections AS (\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND \r\n\t(\r\n\t\t(c.destination_entity_type = 'outbound_rule' AND c.destination_participant_is_incoming = FALSE AND c.termination_reason NOT IN ('cancelled', 'continued_in', 'rejected', 'src_participant_terminated', 'dst_participant_terminated'))\r\n\t\tOR\r\n\t\t(c.destination_entity_type = 'external_line' AND c.destination_participant_is_incoming = FALSE)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY participant_id\r\n\tUNION ALL\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\tmin(c.cdr_started_at) AS started_at\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = FALSE\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY participant_id\r\n)\r\nSELECT\r\n\tTIMESTAMP_TRUNC(i.started_at, HOUR) AS time_bucket,\r\n\tCOUNT(DISTINCT i.participant_id) AS calls\r\nFROM outbound_connections AS i\r\nGROUP BY time_bucket\r\nORDER BY time_bucket\r\n;"
    }
   ]
  },
  {
   "title": "Top anrufende Durchwahlen",
   "type": "barchart",
   "description": "Die Durchwahlen mit den meisten ausgehenden Anrufen",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "-----------------------\r\n-- Outbound connections\r\n-----------------------\r\nWITH outbound_connections AS (\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n    c.destination_participant_id AS extension_participant_id,\r\n\t\tmax(CASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND) AS extension\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND \r\n\t(\r\n\t\t(c.destination_entity_type = 'outbound_rule' AND c.destination_participant_is_incoming = FALSE AND c.termination_reason NOT IN ('cancelled', 'continued_in', 'rejected', 'src_participant_terminated', 'dst_participant_terminated'))\r\n\t\tOR\r\n\t\t(c.destination_entity_type = 'external_line' AND c.destination_participant_is_incoming = FALSE)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n  GROUP BY extension_participant_id\r\n\tUNION ALL\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n    c.source_participant_id AS extension_participant_id,\r\n\t\tmax(CASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND) AS extension\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = FALSE\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tGROUP BY extension_participant_id\r\n)\r\nSELECT\r\n\to.extension,\r\n\tcount(DISTINCT o.extension_participant_id) AS calls\r\nFROM outbound_connections AS o\r\nGROUP BY extension\r\nORDER BY calls DESC\r\nLIMIT 10\r\n;"
    }
   ]
  },
  {
   "title": "Ausgehende Anrufe",
   "type": "table",
   "description": "Detaillierte Liste aller ausgehenden Anrufe im Zeitraum",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "-----------------------\r\n-- Outbound connections\r\n-----------------------\r\nWITH outbound_connections AS (\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_started_at, SECOND) AS duration,\r\n\t\tTIMESTAMP_DIFF(coalesce(c.cdr_answered_at, c.cdr_ended_at), c.cdr_started_at, SECOND) AS ringing_duration,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND) ELSE 0 END AS talking_duration,\r\n\t\tround(coalesce(CAST(b.destination_bill_rate AS numeric), 0.00) * coalesce(TIMESTAMP_DIFF(TIMESTAMP '1970-01-01 00:00:00 UTC' + CAST(b.destination_bill_duration AS interval), TIMESTAMP '1970-01-01 00:00:00 UTC', microsecond) / 60000000, 0.00), 2) AS bill_cost\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tLEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t\tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND \r\n\t(\r\n\t\t(c.destination_entity_type = 'outbound_rule' AND c.destination_participant_is_incoming = FALSE AND c.termination_reason NOT IN ('cancelled', 'continued_in', 'rejected', 'src_participant_terminated', 'dst_participant_terminated'))\r\n\t\tOR\r\n\t\t(c.destination_entity_type = 'external_line' AND c.destination_participant_is_incoming = FALSE)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Source\r\n\t--------------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_started_at, SECOND) AS duration,\r\n\t\tTIMESTAMP_DIFF(coalesce(c.cdr_answered_at, c.cdr_ended_at), c.cdr_started_at, SECOND) AS ringing_duration,\r\n\t\tcoalesce(TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND), 0) AS talking_duration,\r\n\t\tround(coalesce(CAST(b.source_bill_rate AS numeric), 0.00) * coalesce(TIMESTAMP_DIFF(TIMESTAMP '1970-01-01 00:00:00 UTC' + CAST(b.source_bill_duration AS interval), TIMESTAMP '1970-01-01 00:00:00 UTC', microsecond) / 60000000, 0.00), 2) AS bill_cost\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tLEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t\tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND c.source_entity_type = 'external_line'\r\n\tAND c.source_participant_is_incoming = FALSE\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n),\r\nstat AS (\r\n\tSELECT\r\n\t\tROW_NUMBER() OVER(ORDER BY c.started_at DESC) AS id1,\r\n\t\tCASE WHEN (ROW_NUMBER() OVER(PARTITION BY c.main_call_history_id ORDER BY c.started_at DESC) - 1) > 0 THEN 1 ELSE 0 END AS id2,\r\n\t\t*\r\n\tFROM outbound_connections AS c\r\n)\r\nSELECT\r\n\tMOD(c.id1 - SUM(c.id2) OVER(ORDER BY c.started_at DESC), 2) AS gen_call_id,\r\n\tc.main_call_history_id,\r\n\tc.source_participant,\r\n\tc.destination_participant,\r\n\tc.started_at,\r\n\tc.answered_at,\r\n\tc.ended_at,\r\n\tc.duration,\r\n\tc.ringing_duration,\r\n\tc.talking_duration,\r\n\tc.bill_cost\r\nFROM stat AS c\r\nORDER BY c.started_at DESC;"
    }
   ]
  }
 ]
}