{
 "title": "14. Häufige eingehende Anrufer (BigQuery)",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "inbound_caller",
    "label": "Inbound Caller",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Häufige eingehende Anrufer" } },
  {
   "title": "Top 100 häufigste Anrufer (nach Anzahl)",
   "type": "barchart",
   "description": "Die 100 Rufnummern mit den meisten eingehenden Anrufen",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "----------------------\r\n-- Inbound connections\r\n----------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\tc.source_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS participant\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t\tAND c.continued_in_cdr_id IS NULL\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\tc.destination_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS participant\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tc.participant AS participant,\r\n\tCOUNT(DISTINCT c.participant_id) AS participant_count\r\nFROM inbound_connections AS c\r\nGROUP BY c.participant\r\nORDER BY COUNT(DISTINCT c.participant_id) DESC\r\nLIMIT 100\r\n;"
    }
   ]
  },
  {
   "title": "Top 100 häufigste Anrufer (nach Gesprächsdauer)",
   "type": "barchart",
   "description": "Die 100 Rufnummern mit der längsten Gesamtgesprächsdauer",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "----------------------\r\n-- Inbound connections\r\n----------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\tc.source_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS participant,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') AND c.cdr_answered_at IS NOT NULL THEN TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND) ELSE 0 END AS talking_duration\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t\tAND c.continued_in_cdr_id IS NULL\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\tc.destination_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS participant,\r\n\t\tCASE WHEN c.cdr_answered_at IS NOT NULL THEN coalesce(TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND), 0) ELSE 0 END AS talking_duration\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tc.participant AS participant,\r\n\tSUM(c.talking_duration) AS talking_duration\r\nFROM inbound_connections AS c\r\nGROUP BY c.participant\r\nORDER BY SUM(c.talking_duration) DESC\r\nLIMIT 100\r\n;"
    }
   ]
  },
  {
   "title": "Anrufverlauf",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf der Anrufanzahl im gewählten Zeitraum",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "----------------------\r\n-- Inbound connections\r\n----------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.cdr_started_at AS started_at,\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\tc.source_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS participant\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t\tAND c.continued_in_cdr_id IS NULL\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.cdr_started_at AS started_at,\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\tc.destination_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS participant\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\tLEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t\tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tTIMESTAMP_TRUNC(c.started_at, HOUR) AS time,\r\n\tc.participant AS participant,\r\n\tCOUNT(DISTINCT c.participant_id) AS `Calls`\r\nFROM inbound_connections AS c\r\nGROUP BY\r\n\tTIMESTAMP_TRUNC(c.started_at, HOUR),\r\n\tc.participant\r\nORDER BY time\r\n;"
    }
   ]
  },
  {
   "title": "Gesprächsdauer (Verlauf)",
   "type": "timeseries",
   "description": "Zeitlicher Verlauf der Gesprächsdauer häufiger Anrufer",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "----------------------\r\n-- Inbound connections\r\n----------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.cdr_started_at AS started_at,\r\n\t\tc.source_participant_id AS participant_id,\r\n\t\tc.source_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS participant,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') AND c.cdr_answered_at IS NOT NULL THEN TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND) ELSE 0 END AS talking_duration\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t\tAND c.continued_in_cdr_id IS NULL\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.cdr_started_at AS started_at,\r\n\t\tc.destination_participant_id AS participant_id,\r\n\t\tc.destination_participant_phone_number AS participant_phone_number,\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS participant,\r\n\t\tCASE WHEN c.cdr_answered_at IS NOT NULL THEN coalesce(TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND), 0) ELSE 0 END AS talking_duration\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n)\r\nSELECT\r\n\tTIMESTAMP_TRUNC(c.started_at, HOUR) AS time,\r\n\tc.participant AS participant,\r\n\tSUM(c.talking_duration) AS `Talking duration`\r\nFROM inbound_connections AS c\r\nGROUP BY\r\n\tTIMESTAMP_TRUNC(c.started_at, HOUR),\r\n\tc.participant\r\nORDER BY time\r\n;"
    }
   ]
  },
  {
   "title": "Liste eingehender Anrufe",
   "type": "table",
   "description": "Detaillierte Liste aller eingehenden Anrufe der häufigsten Anrufer",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "project": "pbx-26350568",
     "rawSql": "----------------------\r\n-- Inbound connections\r\n----------------------\r\nWITH inbound_connections AS (\r\n\t---------\r\n\t-- Source\r\n\t---------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tcoalesce(c.source_participant_trunk_did, 'Unknown') AS did,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_started_at, SECOND) AS duration,\r\n\t\tTIMESTAMP_DIFF(coalesce(c.cdr_answered_at, c.cdr_ended_at), c.cdr_started_at, SECOND) AS ringing_duration,\r\n\t\tCASE WHEN c.destination_entity_type NOT IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue') THEN TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND) ELSE 0 END AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tLEFT JOIN `3cx_call_data.public_cdroutput` AS c_orig ON\r\n\t\tc_orig.cdr_id = c.originating_cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.source_participant_phone_number = '${inbound_caller:value}')\r\n\tAND\r\n\t(\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type = 'inbound_routing'\r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t\tAND c.termination_reason != 'continued_in'\r\n\t\t\tAND c.continued_in_cdr_id IS NULL\r\n\t\t)\r\n\t\tOR\r\n\t\t(\t\r\n\t\t\tc.source_entity_type = 'external_line' \r\n\t\t\tAND c.destination_entity_type NOT IN ('inbound_routing', 'outbound_rule') \r\n\t\t\tAND c.source_participant_is_incoming = TRUE\r\n\t\t)\r\n\t)\r\n\tAND NOT (c.creation_forward_reason = 'polling' AND c.cdr_answered_at IS NULL AND c_orig.destination_entity_type IN ('group', 'ring_group_ring_all', 'ring_group_hunt', 'queue'))\t\t-- Exclude polling\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n\tUNION ALL\r\n\t--------------\r\n\t-- Destination\r\n\t--------------\r\n\tSELECT\r\n\t\tc.main_call_history_id,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.destination_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.destination_participant_phone_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\t\tELSE c.destination_dn_number || ' ' || coalesce(c.destination_dn_name, 'Unknown')\r\n\t\tEND AS source_participant,\r\n\t\t--\r\n\t\tcoalesce(c.destination_participant_trunk_did, 'Unknown') AS did,\r\n\t\t--\r\n\t\tCASE\r\n\t\t\tWHEN c.source_entity_type = 'external_line'\r\n\t\t\t\tTHEN c.source_participant_phone_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\t\tELSE c.source_dn_number || ' ' || coalesce(c.source_dn_name, 'Unknown')\r\n\t\tEND AS destination_participant,\r\n\t\t--\r\n    c.cdr_started_at AS started_at,\r\n\t\tc.cdr_answered_at AS answered_at,\r\n\t\tc.cdr_ended_at AS ended_at,\r\n\t\tTIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_started_at, SECOND) AS duration,\r\n\t\tTIMESTAMP_DIFF(coalesce(c.cdr_answered_at, c.cdr_ended_at), c.cdr_started_at, SECOND) AS ringing_duration,\r\n\t\tcoalesce(TIMESTAMP_DIFF(c.cdr_ended_at, c.cdr_answered_at, SECOND), 0) AS talking_duration,\r\n\t\t0.00 AS bill_cost\r\n\tFROM `3cx_call_data.public_cdroutput` AS c\r\n\t-- LEFT JOIN `3cx_call_data.public_cdrbilling` AS b ON\r\n\t-- \tb.cdr_id = c.cdr_id\r\n\tWHERE $__timeFilter(c.cdr_started_at)\r\n\tAND ('${inbound_caller:value}' = 'All' OR c.destination_participant_phone_number = '${inbound_caller:value}')\r\n\tAND c.destination_entity_type = 'external_line'\r\n\tAND c.destination_participant_is_incoming\r\n\t--AND c.cdr_answered_at IS NOT NULL\r\n),\r\nstat AS (\r\n\tSELECT\r\n\t\tROW_NUMBER() OVER(ORDER BY c.started_at DESC) AS id1,\r\n\t\tCASE WHEN (ROW_NUMBER() OVER(PARTITION BY c.main_call_history_id ORDER BY c.started_at DESC) - 1) > 0 THEN 1 ELSE 0 END AS id2,\r\n\t\t*\r\n\tFROM inbound_connections AS c\r\n)\r\nSELECT\r\n\tMOD(c.id1 - SUM(c.id2) OVER(ORDER BY c.started_at DESC), 2) AS gen_call_id,\r\n\tc.main_call_history_id,\r\n\tc.source_participant,\r\n\tc.did,\r\n\tc.destination_participant,\r\n\tc.started_at,\r\n\tc.answered_at,\r\n\tc.ended_at,\r\n\tc.duration,\r\n\tc.ringing_duration,\r\n\tc.talking_duration,\r\n\tc.bill_cost\r\nFROM stat AS c\r\nORDER BY c.started_at DESC\r\n;"
    }
   ]
  }
 ]
}