apiVersion: v1
kind: Service
metadata:
  name: 3cx-dashboard
  namespace: 3cx-dashboard
  labels:
    app: 3cx-dashboard
spec:
  type: LoadBalancer
  selector:
    app: 3cx-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 3031
      protocol: TCP
