apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 3cx-dashboard-arconda-settings
  namespace: mandant-arconda
  labels:
    app: 3cx-dashboard-arconda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
